---
settings:
  name: FlexPod
  internal:
    pdf_enabled: true
  prod:
    pdf_enabled: true
    harmony_enabled: true
sidebar:
  entries:
    - title: FlexPod Solutions Documentation
      url: /index.html
    - section: fp-def
    - section: flexpod-dc
    - section: hybrid-cloud
    - section: ent-db
    - section: healthcare
    - section: vdi
    - section: modern-apps
    - section: ms-apps
    - section: express
    - section: security
    - section: ontap-connector-for-intersight
    - section: infrastructure

homepage:
  tiles:
    - title: FlexPod - Start Here
      links:
        - title: "Videos and Demos"
          summary:
          url: https://tv.netapp.com/search?q=FlexPod
        - title: "Blogs"
          summary:
          url: https://blog.netapp.com/tag/Flexpod/

    - title: AI and Modern Data Analytics with FlexPod
      links:
        - title: "What's New"
          summary:
          url: https://www.flexpod.com/solutions/use-cases/machine-learning/
        - title: "Videos and Demos"
          summary:
          url: https://tv.netapp.com/search?q=FlexPod%20AI
        - title: "Blogs"
          summary:
          url: https://blog.netapp.com/tag/Flexpod/

    - title: FlexPod Business Applications and Enterprise Databases
      links:
        - title: "Videos and Demos"
          summary:
          url: https://tv.netapp.com/search?q=FlexPod%20SAP
        - title: "Blogs"
          summary:
          url: https://blog.netapp.com/tag/Flexpod/

    - title: Hybrid Cloud with FlexPod
      links:
        - title: "What's New"
          summary:
          url: https://flexpod.com/solutions/use-cases/hybrid-cloud/
        - title: "Videos and Demos"
          summary:
          url: https://tv.netapp.com/search?q=FlexPod%20Hybrid%20Cloud
        - title: "Blogs"
          summary:
          url: https://blog.netapp.com/tag/Flexpod/

    - title: FlexPod for VDI
      links:
        - title: "What's New"
          summary:
          url: https://www.flexpod.com/solutions/use-cases/virtual-desktop-infrastructure/
        - title: "Videos and Demos"
          summary:
          url: https://tv.netapp.com/search?q=FlexPod%20VDI
        - title: "Blogs"
          summary:
          url: https://blog.netapp.com/tag/Flexpod/

    - title: Healthcare with FlexPod
      links:
        - title: "What's New"
          summary:
          url: https://flexpod.com/solutions/verticals/healthcare/
        - title: "Videos and Demos"
          summary:
          url: https://tv.netapp.com/search?q=FlexPod%20Healthcare
        - title: "Blogs"
          summary:
          url: https://blog.netapp.com/tag/Healthcare/
