sidebar:
  entries:
    - title: FlexPod Solutions Documentation
      url: /index.html
    - section: ontap-connector-for-intersight
    - section: express-c-series-c190-design
    - section: express-c-series-aff220-design
    - section: express-c-series-aff220-deploy
    - section: express-direct-attach-design
