sidebar:
  entries:
    - title: FlexPod Solutions Documentation
      url: /index.html
    - section: fp-def
    - section: hybrid-cloud
    - section: ent-db
    - section: healthcare
    - section: vdi
    - section: modern-apps
    - section: ms-apps
    - section: express
    - section: security
    - section: ontap-connector-for-intersight
