sidebar:
  entries:
    - title: FlexPod Solutions Documetation
      url: /index.html
    - section: ontap-connector-for-insight
    - section: express-c-series-aff220-design
    - section: express-c-series-c190-design
    - section: express-direct-attach-design

homepage:
  tiles:
    - title: 
