---
settings:
  name: FlexPod
  internal:
    pdf_enabled: true
  prod:
    pdf_enabled: true
    harmony_enabled: true
sidebar:
  entries:
    - title: FlexPod Solutions Documentation
      url: /index.html
    - section: fp-def
    - section: flexpod-dc
    - section: hybrid-cloud
    - section: ent-db
    - section: healthcare
    - section: vdi
    - section: modern-apps
    - section: express
    - section: security
    - section: ontap-connector-for-intersight
    - section: infrastructure
    - title: Legal notices
      url: /legal-notices.html
