---
sidebar: sidebar
permalink: fp-def/dc-tech-spec_solution_overview.html
keywords: flexpod, datacenter, technucal, specifications, platform, architecture
summary: The FlexPod platform is a predesigned, best practice data center architecture that is built on the Cisco Unified Computing System (Cisco UCS), the Cisco Nexus family of switches, and NetApp storage controllers (NetApp AFF, ASA, FAS or AFX systems).
---

= FlexPod Datacenter Technical Specifications
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ./../media/


[.lead]
The FlexPod platform is a predesigned, best practice data center architecture that is built on the Cisco Unified Computing System (Cisco UCS), the Cisco Nexus family of switches, and NetApp storage controllers (AFF, ASA, FAS, or AFX systems).

FlexPod is a suitable platform for running a variety of virtualization hypervisors as well as bare-metal operating systems and enterprise workloads. FlexPod delivers not only a baseline configuration, but also the flexibility to be sized and optimized to accommodate many different use cases and requirements.

[NOTE]
Before you order a complete FlexPod configuration, see the http://www.netapp.com/us/technology/flexpod[FlexPod Converged Infrastructure^] page on netapp.com for the latest version of these technical specifications.


link:dc-tech-spec_flexpod_platforms.html[Next: FlexPod platforms.]
