---
sidebar: sidebar
permalink: fp-def/dc-tech-spec_minimum_hardware_requirements.html
keywords: minimum, hardware, requirements, switches, fabric, interconnects, servers, storage, controllers
summary: A FlexPod Datacenter configuration has minimum hardware requirements, including, but not limited to, switches, fabric interconnects, servers, and NetApp storage controllers.
---

= Minimum hardware requirements
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ./../media/


[.lead]
A FlexPod Datacenter configuration has minimum hardware requirements, including, but not limited to, switches, fabric interconnects, servers, and NetApp storage controllers.

A FlexPod configuration has the following minimum hardware requirements:

* Two Cisco Nexus switches in a redundant configuration. This configuration can consist of two redundant switches from the Cisco Nexus 9000 Series mentioned earlier. The two switches should be of the same model and should be configured in the same mode of operation.

[NOTE]
    If you are deploying an ACI architecture, you must observe the following additional requirements:
        * Deploy the Cisco Nexus 9000 Series Switches in a leaf-spine topology.
        * Use three Cisco Application Policy Infrastructure Controllers (APICs).

* Two Cisco UCS 6400, 6500, or 6600 Series Fabric Interconnects in a redundant configuration, if using the UCS C-Series Rack Servers or the X-Series Modular systems.

* Two Cisco UCS C-Series rack servers with FI connectivity with Intersight-managed configuration (IMM), or the Cisco UCS X-Series Direct with Cisco IMM, or the Cisco UCS X-Series Modular with Cisco Intersight-managed configuration(IMM). 

[NOTE]
    If you are using the UCS rack servers without FI connectivity, you could use CIMC or the Intersight standalone mode for management.

* Two NetApp AFF, NetApp ASA, or NetApp FAS controllers in a high-availability (HA) pair configuration deployed as a two-node cluster. If using NetApp AFX, a minimum of four NetApp AFX controllers are required and is to be deployed as a four-node HA cluster along with a pair of cluster interconnect switches.

* A minimum of one NetApp disk shelf is required for the storage controllers that do not have a built-in disk shelf.
