---
sidebar: sidebar
permalink: fp-def/dc-tech-spec_technical_specifications_and_references.html
keywords: cisco, ucs, c-series, x-series, x-series-direct, vic, disk shelves, nexus, aff, asa, fas, afx
summary: Technical specifications provide details about the hardware components in a FlexPod solution, such as chassis, servers, switches, and storage controllers.
---

= Technical specifications and references
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ./../media/


[.lead]
Technical specifications provide details about the hardware components in a FlexPod solution, such as chassis, servers, switches, and storage controllers.

== Cisco UCS fabric interconnects

The technical specifications for Cisco UCS fabric interconnect include form factor, the total number of ports and expansion slots, and throughput capacity. Refer to the table below for Cisco UCS fabric interconnect datasheets.

|===
|Component |Cisco UCS datasheet

|Cisco UCS 6664
.2+| https://www.cisco.com/c/dam/en/us/products/collateral/servers-unified-computing/ucs-x-series-modular-system/ucs-6600-series-fabric-interconnect-specsheet.pdf[Cisco UCS 6600 Series Fabric Interconnects]
|Cisco UCS 6652
|Cisco UCS 6536
|
https://www.cisco.com/c/dam/en/us/products/collateral/servers-unified-computing/ucs-x-series-modular-system/cisco-ucs-6536-fabric-interconnect-spec-sheet.pdf[Cisco UCS 6536 Fabric Interconnect]
|Cisco UCS 6454
.2+|
https://www.cisco.com/c/dam/en/us/products/collateral/servers-unified-computing/ucs-b-series-blade-servers/6400-specsheet.pdf[Cisco UCS 6400 Series Fabric Interconnects]
|Cisco UCS 64108
|Cisco UCS 9108 100G Fabric Interconnect
|
https://www.cisco.com/c/dam/en/us/products/collateral/servers-unified-computing/ucs-x-series-modular-system/ucs-fabric-interconnect-9108-100g.pdf[Cisco UCS 9108 100G Fabric Interconnect for Cisco UCS X-Series Direct]

|===


== Cisco UCS X-Series chassis

The technical specifications for Cisco UCS X-Series chassis, as shown in the table below, include the following components:

* Number of rack units
* Maximum number of nodes
* Unified Fabric capability
* Number of I/O bays for IFMs

|===
|Component |Cisco UCS X9508 chassis

|Rack units
|7
|Maximum number of nodes
|8
|Capable of Unified Fabric
|Yes
|I/O bays for IFMs
|Two bays for Cisco UCS 9108 Intelligent Fabric Modules (IFMs)

|===

For more information, see the link:https://www.cisco.com/c/en/us/products/collateral/servers-unified-computing/ucs-x-series-modular-system/datasheet-c78-2472574.html[Cisco UCS X9508 X-Series Chassis Datasheet^].

== Cisco UCS X-Series compute node

The technical specifications for Cisco UCS X-Series compute node include the following components:

* Number of processor sockets
* Processor support
* Memory capacity
* Size and speed
* SAN boot support
* Number of mezzanine adapter slots
* I/O maximum throughput
* Form factor
* Maximum number of compute nodes per chassis

Refer to the table below for the technical specifications for Cisco UCS X-Series compute nodes.

|===
|Component | Cisco UCS datasheet
|Cisco UCS X210c M7
|
https://www.cisco.com/c/en/us/products/collateral/servers-unified-computing/ucs-x-series-modular-system/ucs-x210c-m7-compute-node-ds.html[Cisco UCS X210c M7 Compute Node]
|Cisco UCS X210c M8
|
https://www.cisco.com/c/en/us/products/collateral/servers-unified-computing/ucs-x-series-modular-system/ucs-x210c-m8-compute-node-ds.html[Cisco UCS X210c M8 Compute Node]
|Cisco UCS X215c M8
|
https://www.cisco.com/c/en/us/products/collateral/servers-unified-computing/ucs-x-series-modular-system/ucs-x215c-m8-compute-node-ds.html[Cisco UCS X215c M8 Compute Node]
|Cisco UCS X410c M7
|
https://www.cisco.com/c/en/us/products/collateral/servers-unified-computing/ucs-x-series-modular-system/ucs-x410c-m7-compute-node-ds.html[Cisco UCS X410c M7 Compute Node]
|Cisco UCS X410c M8
|
https://www.cisco.com/c/en/us/products/collateral/servers-unified-computing/ucs-x-series-modular-system/ucs-x410c-m8-compute-node-ds.html[Cisco UCS X410c M8 Compute Node]
|===

== Cisco UCS C-Series rack servers

The technical specifications for the Cisco UCS C-Series rack servers include processor support, maximum memory capacity, the number of PCIe slots, and form factor. For additional details on compatible UCS server models, see the https://ucshcltool.cloudapps.cisco.com/public/[Cisco Hardware Compatibility^] list. 

Refer to the table below for the technical specifications for Cisco UCS C-Series rack servers.

|===
|Component |Cisco UCS datasheet

|Cisco UCS C220 M7
|
https://www.cisco.com/c/en/us/products/collateral/servers-unified-computing/ucs-c-series-rack-servers/ucs-c220-m7-rack-server-ds.html[Cisco UCS C220 M7 Rack Server]
|Cisco UCS C220 M8
|
https://www.cisco.com/c/en/us/products/collateral/servers-unified-computing/ucs-c-series-rack-servers/ucs-c220-m8-rack-server-ds.html[Cisco UCS C220 M8 Rack Server]
|Cisco UCS C225 M6
|
https://www.cisco.com/c/en/us/products/collateral/servers-unified-computing/ucs-c-series-rack-servers/ucs-c225-m6-sff-rack-server-ds.html[Cisco UCS C225 M6 Rack Server]
|Cisco UCS C240 M7
|
https://www.cisco.com/c/en/us/products/collateral/servers-unified-computing/ucs-c-series-rack-servers/ucs-c240-m7-rack-server-ds.html[Cisco UCS C240 M7 Rack Server]
|Cisco UCS C240 M8
|
https://www.cisco.com/c/en/us/products/collateral/servers-unified-computing/ucs-c-series-rack-servers/ucs-c240-m8-rack-server-ds.html[Cisco UCS C240 M8 Rack Server]
|Cisco UCS C245 M6
|
https://www.cisco.com/c/en/us/products/collateral/servers-unified-computing/ucs-c-series-rack-servers/ucs-c245-m6-sff-rack-server-ds.html[Cisco UCS C245 M6 Rack Server]
|Cisco UCS C245 M8
|
https://www.cisco.com/c/en/us/products/collateral/servers-unified-computing/ucs-c-series-rack-servers/ucs-c245-m8-rack-server-ds.html[Cisco UCS C245 M8 Rack Server]
|===


Refer to the table below for the technical specifications and GPU options for Cisco UCS C-Series rack servers optimized for AI use cases.

|===
|Cisco UCS C-Series rack server|Technical specifications

|Cisco UCS C845A M8
|
https://www.cisco.com/c/en/us/products/collateral/servers-unified-computing/ucs-c-series-rack-servers/ucs-c845a-m8-rack-server-ds.html[Cisco UCS C845A M8 Rack Server]
|Cisco UCS C880A M8
|
https://www.cisco.com/c/en/us/products/collateral/servers-unified-computing/ucs-c-series-rack-servers/ucs-c880a-m8-rack-server-ds.html[Cisco UCS C880A M8 Rack Server]
|Cisco UCS C885A M8
|
https://www.cisco.com/c/en/us/products/collateral/servers-unified-computing/ucs-c-series-rack-servers/ucs-c885a-m8-ds.html[Cisco UCS C885A M8 Rack Server]
|===


== Cisco UCS VIC adapters

The technical specifications for Cisco UCS Virtual Interface Card (VIC) adapters for Cisco Servers include the following components:

* Number of uplink ports
* Performance per port (IOPS)
* Power
* Number of blade ports
* Hardware offload
* Single root input/output virtualization (SR-IOV) support

All currently validated FlexPod architectures use a Cisco UCS VIC. Other adapters are supported if they are listed on the NetApp http://mysupport.netapp.com/matrix[IMT^] and are compatible with your deployment of FlexPod, but they might not deliver all the features that are outlined in corresponding reference architectures. The following table illustrates the Cisco UCS VIC adapter datasheets.

|===
|Component |Cisco UCS datasheet

|Cisco UCS Virtual Interface Adapters
|
https://www.cisco.com/site/us/en/products/computing/servers-unified-computing-systems/fabric-interconnects-extenders/index.html#accordion-b3f362d53d-item-2d9aa2ccfd[Cisco UCS VIC Datasheets]
|===


== Cisco Nexus switches

The technical specifications for Cisco Nexus Switches are contained in the datasheet for each model. Specifications include the form factor size; the number of supervisors, fabric module, and line card slots; and the maximum number of ports. These datasheets can be found in the following table.

|===
|Component |Cisco Nexus datasheet

|Cisco Nexus 9200 Series
|
https://www.cisco.com/c/en/us/products/collateral/switches/nexus-9000-series-switches/datasheet-c78-735989.html[Cisco Nexus 9200 Series Switches]
|Cisco Nexus 9300 Series
|
https://www.cisco.com/c/en/us/products/collateral/switches/nexus-9000-series-switches/datasheet-c78-736967.html[Cisco Nexus 9300 Series Switches]
|Cisco Nexus 9400 Series
|
https://www.cisco.com/c/en/us/products/collateral/switches/nexus-9000-series-switches/nexus9400-series-switches-ds.html[Cisco Nexus 9400 Series Switches]
|Cisco Nexus 9500 Series
|
https://www.cisco.com/c/en/us/products/collateral/switches/nexus-9000-series-switches/datasheet-c78-729404.html[Cisco Nexus 9500 Series Switches]   
|Cisco Nexus 9800 Series
|
https://www.cisco.com/c/en/us/products/collateral/switches/nexus-9000-series-switches/nexus9800-series-switches-ds.html[Cisco Nexus 9800 Series Switches]
|===

== Cisco MDS options

The technical specifications for Cisco Nexus Switches are contained in the datasheet for each model which are listed in the following table.

|===
|Cisco MDS Switch |Description

|Cisco MDS 9100 Series Switches
|
http://www.cisco.com/c/en/us/products/storage-networking/mds-9100-series-multilayer-fabric-switches/datasheet-listing.html[Cisco MDS 9100 Series Switches]
|Cisco MDS 9200 Series Switches
|
https://www.cisco.com/c/en/us/products/storage-networking/mds-9200-series-multiservice-switches/datasheet-listing.html[Cisco MDS 9200 Series Switches]
|Cisco MDS 9300 Series Switches
|
https://www.cisco.com/c/en/us/products/storage-networking/mds-9300-series-multilayer-fabric-switches/datasheet-listing.html[Cisco MDS 9300 Series Switches]
|Cisco MDS 9700 Series directors
|
http://www.cisco.com/c/en/us/products/storage-networking/mds-9700-series-multilayer-directors/datasheet-listing.html[Cisco MDS 9700 Series Switches]
|===

== Cisco Application Policy Infrastructure controller

When you deploy Cisco ACI, you must configure three Cisco APICs. The following table lists the Cisco APIC datasheet.

|===
|Component |Cisco Application Policy Infrastructure datasheet

|Cisco Application Policy Infrastructure Controller
|
https://www.cisco.com/c/en/us/products/collateral/cloud-systems-management/application-policy-infrastructure-controller-apic/datasheet-c78-739715.html[Cisco APIC Datasheet]
|===

== SFP modules

For information about the SFP modules, review the following resources:

* For information about the Cisco 10Gb SFP, see https://www.cisco.com/c/en/us/products/interfaces-modules/10-gigabit-modules/index.html[Cisco 10 Gigabit Modules^].
* For information about the Cisco 25Gb SFP, see https://www.cisco.com/c/en/us/products/interfaces-modules/25-gigabit-modules/index.html[Cisco 25 Gigabit Modules^].
* For information about the Cisco QSFP module, see the https://www.cisco.com/c/en/us/products/collateral/interfaces-modules/transceiver-modules/data_sheet_c78-660083.html[Cisco 40GBASE QSFP Modules datasheet^].
* For information about the Cisco 100Gb SFP, see https://www.cisco.com/c/en/us/products/interfaces-modules/100-gigabit-modules/index.html[Cisco 100 Gigabit Modules^].
* For information about the Cisco 200GB QSFP, see https://www.cisco.com/c/en/us/products/collateral/interfaces-modules/transceiver-modules/nb-06-200g-qsfp56-cables-trans-mod-ds-cte-en.html[Cisco 200G QSFP56 Modules datasheet^].
* For information about the Cisco 400GB QSFP, see https://www.cisco.com/c/en/us/products/collateral/interfaces-modules/transceiver-modules/datasheet-c78-743172.html[Cisco 400G QSFP56 Modules datasheet^].
* For information about the Cisco FC SFP module, see the https://www.cisco.com/c/en/us/products/collateral/storage-networking/mds-9000-series-multilayer-switches/product_data_sheet09186a00801bc698.html?dtid=osscdc000283[Cisco MDS 9000 Family Pluggable Transceivers datasheet^].
* For information about all supported Cisco SFP and transceiver modules, see http://www.cisco.com/en/US/docs/interfaces_modules/transceiver_modules/installation/note/78_15160.html[Cisco SFP and SFP+ Transceiver Module Installation Notes^] and http://www.cisco.com/en/US/products/hw/modules/ps5455/prod_module_series_home.html[Cisco Transceiver Modules^].


== NetApp storage controllers

The technical specifications for NetApp storage controllers include the platform configuration, max raw capacity, memory, form factor, ONTAP version requirements, disk shelves, etc.

=== NetApp AFF A-Series 

NetApp AFF A-Series storage controllers are supported for use in FlexPod Datacenter. Additional information can be found in the https://www.netapp.com/pdf.html?item=/media/7828-ds-3582-aff-a-series-ai-era.pdf[AFF A-series Technical Specifications^] datasheet and in the https://hwu.netapp.com/[NetApp Hardware Universe^]. See the platform-specific documentation listed in the following table for detailed information about a specific AFF Model.

|===
|Component |AFF A-Series controller platform documentation

|NetApp AFF A50
|
https://docs.netapp.com/us-en/ontap-systems/a20-30-50/a50-key-specifications.html[AFF A50 Key Specifications]
|NetApp AFF A70
|
https://docs.netapp.com/us-en/ontap-systems/a70-90/a70-key-specifications.html[AFF A70 Key Specifications]
|NetApp AFF A90
|
https://docs.netapp.com/us-en/ontap-systems/a70-90/a90-key-specifications.html[AFF A90 Key Specifications]
|NetApp AFF A1K
|
https://docs.netapp.com/us-en/ontap-systems/a1k/overview.html[AFF A1K Key Specifications]
|===

=== NetApp AFF C-Series 

NetApp AFF C-Series storage controllers are supported for use in FlexPod Datacenter. Additional information can be found in the https://www.netapp.com/pdf.html?item=/media/81583-ds-4240-aff-c-series.pdf[AFF C-Series Technical Specifications^] datasheet and in the https://hwu.netapp.com/[NetApp Hardware Universe^]. See the platform- specific documentation listed in the following table for detailed information about a specific AFF Model.

|===
|Component |AFF C-Series controller platform documentation

|NetApp AFF C60
|
https://docs.netapp.com/us-en/ontap-systems/c30-60/c60-key-specifications.html[AFF C60 Key Specifications]
|NetApp AFF C80
|
https://docs.netapp.com/us-en/ontap-systems/c80/overview.html[AFF C80 Key Specifications]
|===

=== NetApp ASA

NetApp ASA storage controllers are supported for use in FlexPod Datacenter. Additional information can be found in the https://www.netapp.com/pdf.html?item=/media/85736-ds-4254-asa.pdf[NetApp ASA Technical Specifications^] datasheet and in the https://hwu.netapp.com/[NetApp Hardware Universe^]. See the platform- specific documentation listed in the following table for detailed information about a specific ASA Model.

|===
| Component | NetApp ASA controller platform documentation

|NetApp ASA A50 | https://docs.netapp.com/us-en/ontap-systems/asa-r2-key-specifications/asa-a50-key-specifications.html[ASA A50 Key Specifications]
|NetApp ASA A70 | https://docs.netapp.com/us-en/ontap-systems/asa-r2-key-specifications/asa-a70-key-specifications.html[ASA A70 Key Specifications]
|NetApp ASA A90 | https://docs.netapp.com/us-en/ontap-systems/asa-r2-key-specifications/asa-a90-key-specifications.html[ASA A90 Key Specifications]
|NetApp ASA A1K | https://docs.netapp.com/us-en/ontap-systems/asa-r2-key-specifications/asa-a1k-key-specifications.html[ASA A1K Key Specifications]
|===

=== NetApp FAS Series

FAS storage controllers are supported for use in FlexPod Datacenter. Additional information can be found in link:https://www.netapp.com/pdf.html?item=/media/7819-ds-4020.pdf[NetApp FAS Technical Specifications^] and the https://hwu.netapp.com/[NetApp Hardware Universe^]. See the platform-specific documentation listed in the following table for detailed information about a specific FAS model.

|===
|Component |FAS Series controller platform documentation

|NetApp FAS70|https://docs.netapp.com/us-en/ontap-systems/fas-70-90/fas70-key-specifications.html[FAS70 Key Specifications^]
|NetApp FAS90|https://docs.netapp.com/us-en/ontap-systems/fas-70-90/fas90-key-specifications.html[FAS90 Key Specifications^]
|===

=== NetApp AFX

NetApp AFX storage controllers are supported for use in FlexPod Datacenter. Additional information can be found in the https://www.netapp.com/pdf.html?item=/media/142853-ds-3466-netapp-afx-datasheet.pdf[NetApp AFX Technical Specifications^] datasheet and in the https://hwu.netapp.com/[NetApp Hardware Universe^]. See the platform-specific documentation listed in the following table for detailed information about a specific AFX Model.

|===
| Component | NetApp AFX controller platform documentation
|NetApp AFX 1K 
.2+| https://docs.netapp.com/us-en/ontap-systems/afx/index.html[AFX Documentation]
|NetApp AFX 2K 
|===

=== NetApp disk shelves

The technical specifications for NetApp disk shelves include the form factor size, the number of drives per enclosure, and the shelf I/O modules; this documentation can be found in the following table. For more information, refer to the https://hwu.netapp.com/[NetApp Hardware Universe^].

|===
|Component |NetApp FAS/AFF disk shelf documentation

|NetApp DS212C Disk Shelf
.6+|https://www.netapp.com/data-storage/disk-shelves-storage-media/[NetApp Disk Shelf Documentation]
|NetApp DS224C Disk Shelf
|NetApp DS460C Disk Shelf
|NetApp NS224 Disk Shelf
|NetApp NS224 w/NSM 100B Disk Shelf
|NetApp NX224 Disk Shelf
|===

=== NetApp drives

The technical specifications for NetApp drives include the form factor size, disk capacity, disk RPM, supporting controllers, and ONTAP version requirements. These specifications can be found in the Drives section of the http://hwu.netapp.com/Drives/Index?queryId=1581392[NetApp Hardware Universe^].