---
sidebar: sidebar
permalink: fp-def/dc-tech-spec_power_and_cabling_requirements.html
keywords: power, cabling, requirements, flexpod, datacenter, netapp, cisco, ucs, disk shelves
summary: This section describes the power requirements and disk shelf cabling guidelines for a FlexPod Datacenter design.
---

= Power and cabling guidelines
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ../media/


[.lead]
This section describes the power requirements and cabling guidelines for a FlexPod Datacenter design.

== Power requirements

Power requirements for FlexPod Datacenter differ based on the location where the FlexPod Datacenter configuration is installed.

For more data about the maximum power that is required and for other detailed power information, consult the technical specifications for each hardware component listed in the section link:dc-tech-spec_technical_specifications_and_references.html[Technical Specifications and References: Hardware Components].

For detailed Cisco UCS power data, see the https://ucspowercalculator.cisco.com/[Cisco UCS power calculator^].

For NetApp storage controller power data, see the https://hwu.netapp.com/[NetApp Hardware Universe^]. Under *Platforms*, select the storage platform you want to use (for example, AFF A90), select the ONTAP version, and then click *Show Results*. Power cord data is listed in the *Supported Power Cords* section. For details on size, weight, wattage etc., refer to the *Size, Weight, Acoustic, Power* section. 

== Cabling guidelines

This section provides general cabling guidelines for a FlexPod Datacenter design.

* Ensure redundant connectivity for the compute and storage connections. 
* The speed of the connections needs to be compatible with the connected components.
* Refer to the link:https://docs.netapp.com/us-en/flexpod/fp-def/dc-tech-spec_topologies.html[FlexPod Datacenter topologies^] section for additional cabling guidelines for specific topologies.

The following table provides cabling guidelines for NetApp disk shelves that can be used in a FlexPod Datacenter design.

|===
|Disk shelf |Cabling guidelines
|DS212C
.3+|link:https://docs.netapp.com/us-en/ontap-systems/sas3/install-cabling-rules.html#configuration-rules[SAS cabling rules^]
|DS224C
|DS460C
|NS224
.3+|link:https://docs.netapp.com/us-en/ontap-systems/drive-shelves/index.html[NS224 and NX224 shelf requirements and best practices^]
|NS224 w/NSM100B
|NX224
|===
