---
sidebar: sidebar
permalink: fp-def/dc-tech-spec_cisco_components.html
keywords: cisco, components, ucs, fabric, interconnect, server, rack, apic, nexus, software, support, mds, x-series-modular, x-series-direct
summary: Cisco has contributed substantially to the FlexPod design and architecture, covering both the compute and networking layers of the solution. This section describes the Cisco UCS and Cisco Nexus options that are available for FlexPod.
---

= Cisco components
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ./../media/


[.lead]
Cisco has contributed substantially to the FlexPod design and architecture, covering both the compute and networking layers of the solution. This section describes the Cisco UCS and Cisco Nexus options that are available for FlexPod.


== Cisco UCS fabric interconnect options

Redundant fabric interconnects are required in the FlexPod architecture. When you add multiple Cisco UCS chassis to a pair of fabric interconnects, remember that the maximum number of chassis in an environment is determined by both an architectural and a port limit.

The part numbers that are shown in the following table are for the base fabric interconnects. They do not include the power supply unit (PSU) or SFP+, QSFP+, or expansion modules.

|===
|Cisco UCS fabric interconnect |Part number |Technical specifications

|Cisco UCS 6664
|UCS-FI-6664-U
.2+|
https://www.cisco.com/c/en/us/products/collateral/servers-unified-computing/ucs-6600-series-fabric-interconnect-ds.html[Cisco UCS 6600 Series Fabric Interconnect]
|Cisco UCS 6652
|UCS-FI-6652-U
|Cisco UCS 6536
|UCSX-FI-6536-U
|
https://www.cisco.com/c/en/us/products/collateral/servers-unified-computing/ucs6536-fabric-interconnect-ds.html[Cisco UCS 6536 Fabric Interconnect]
|Cisco UCS 6454
|UCS-FI-6454-U
.2+|
https://www.cisco.com/c/en/us/products/collateral/servers-unified-computing/datasheet-c78-741116.html[Cisco UCS 6400 Series Fabric Interconnect]
|Cisco UCS 64108
|UCS-FI-64108-U
|UCS 9108 100G Fabric Interconnect (Cisco UCS X-Series Direct)
|UCSX-S9108-100G
|
https://www.cisco.com/c/dam/en/us/products/collateral/servers-unified-computing/ucs-x-series-modular-system/ucs-fabric-interconnect-9108-100g.pdf[Cisco UCS 9108 Fabric Interconnect]
|===


== Cisco UCS X-Series chassis option

To use Cisco UCS X-Series compute nodes, you must have a Cisco UCS X-Series chassis. The following table describes the Cisco UCS X-Series chassis option.

|===
|Cisco UCS X-Series blade |Part number |Technical specifications

|Cisco UCS X9508 Chassis
|UCSX-9508
|
https://www.cisco.com/c/en/us/products/collateral/servers-unified-computing/ucs-x-series-modular-system/datasheet-c78-2472574.html?ccid=cc002456&oid=dstcsm026317[Cisco UCS X9508 Chassis]
|===

Each Cisco UCS 9508 chassis must have two Cisco UCS 9108 Intelligent Fabric Modules (IFMs) to provide redundant connectivity to the fabric interconnects.

== Cisco UCS X-Series device options

Cisco UCS X-Series compute nodes are available with various CPU, memory, and I/O options. The part numbers listed in the following table are for the base node. They do not include the CPU, memory, drives, or mezzanine adapter cards. Multiple configuration options are available and are supported in the FlexPod architecture.

|===
|Cisco UCS X-Series compute nodes |Part number |Technical specifications

|Cisco UCS X210c M7
|UCSX-210C-M7
|
https://www.cisco.com/c/en/us/products/collateral/servers-unified-computing/ucs-x-series-modular-system/ucs-x210c-m7-compute-node-ds.html[Cisco UCS X210c M7 Compute Node]
|Cisco UCS X210c M8
|UCSX-210C-M8
|
https://www.cisco.com/c/en/us/products/collateral/servers-unified-computing/ucs-x-series-modular-system/ucs-x210c-m8-compute-node-ds.html[Cisco UCS X210c M8 Compute Node]
|Cisco UCS X215c M8
|UCSX-215C-M8
|
https://www.cisco.com/c/en/us/products/collateral/servers-unified-computing/ucs-x-series-modular-system/ucs-x215c-m8-compute-node-ds.html[Cisco UCS X215c M8 Compute Node]
|Cisco UCS X410c M7
|UCSX-410C-M7
|
https://www.cisco.com/c/en/us/products/collateral/servers-unified-computing/ucs-x-series-modular-system/ucs-x410c-m7-compute-node-ds.html[Cisco UCS X410c M7 Compute Node]
|Cisco UCS X410c M8
|UCSX-410C-M8
|
https://www.cisco.com/c/en/us/products/collateral/servers-unified-computing/ucs-x-series-modular-system/ucs-x410c-m8-compute-node-ds.html[Cisco UCS X410c M8 Compute Node]
|===

The below table lists the PCI Express Nodes available for the Cisco UCS X-Series chassis.

|===
|Cisco UCS X-Series PCIe nodes |Part number |Technical specifications

|Cisco UCS X580p PCIe Node
|UCSX-580P-U
|
https://www.cisco.com/c/en/us/products/collateral/servers-unified-computing/ucs-x-series-modular-system/ucs-x580p-pcie-node-ds.html[Cisco UCS X580p PCIe Node]
|Cisco UCS X440p PCIe Node
|UCSX-440P
|
https://www.cisco.com/c/en/us/products/collateral/servers-unified-computing/ucs-x-series-modular-system/ucs-x440p-pcle-node-ds.html[Cisco UCS X440p PCIe Node]
|===

The table below lists the X-Fabric Modules available for the Cisco UCS X-Series chassis.

|===
|Cisco UCS X-Series X-Fabric Modules |Part number |Technical specifications

|Cisco UCS 9108 Intelligent Fabric Module
|UCSX-I-9108-100G
|
https://www.cisco.com/c/dam/en/us/products/collateral/servers-unified-computing/ucs-x-series-modular-system/cisco-ucs-9108-100g-intelligent-fabric-module-spec-sheet.pdf[Cisco UCS 9108 Intelligent Fabric Module]
|Cisco UCS X9516 X-Fabric Module
|UCSX-FS-9516
|
https://www.cisco.com/c/en/us/products/collateral/servers-unified-computing/ucs-x-series-modular-system/ucs-9516-x-fabric-module-ds.html[Cisco UCS X9516 X-Fabric Module]
|Cisco UCS X9416 X-Fabric Module
|UCSX-F-9416
|
https://www.cisco.com/c/en/us/products/collateral/servers-unified-computing/ucs-x-series-modular-system/solution-overview-c22-2432175.html?ccid=cc002456&oid=sowcsm025665[Cisco UCS X9416 X-Fabric Module]
|===


== Cisco UCS X-Series Modular System

The Cisco UCS X-Series Modular System begins with the Cisco UCS X9508 Server Chassis engineered to be adaptable and future-ready. The chassis has a unified Ethernet fabric with Cisco UCS Intelligent Fabric Modules and Cisco UCS X-Fabric Technology for other technologies. At the top rear of the chassis are two intelligent fabric modules that connect the chassis to upstream Cisco UCS 6400, 6500, and UCS 6600 Series Fabric Interconnects. 

For a quick overview of Cisco UCS X-Series capabilities and features, see link:https://www.cisco.com/c/en/us/products/collateral/servers-unified-computing/ucs-x-series-modular-system/ucs-x-series-modular-system-aag.html[Cisco UCS X-Series Modular At-a-Glance^].

The Cisco UCS X215c M8, Cisco UCS X210c Compute Nodes, and Cisco UCS X410c Compute Nodes provide the functionalities of both blade and rack servers by offering compute density, storage capacity, and expandability in a single form factor.

The Cisco UCS X440p PCIe Node supports adding GPUs with PCIe Gen 4.0 with the Cisco UCS X9416 X-Fabric Module. The Cisco UCS X580p PCIe Node supports adding GPUs with PCIe Gen 5.0 with the Cisco UCS X9516 X-Fabric Module


Refer to the technical specifications for each of these components in the sections above for more information about the Cisco UCS X-Series Modular System solution components.

[NOTE]
Refer to this link for the complete technical specification for UCS X-Series Modular System link:https://www.cisco.com/c/en/us/products/servers-unified-computing/ucs-x-series-modular-system/datasheet-listing.html[Cisco UCS X-Series Modular Sysytem^]


== Cisco UCS X-Series Direct options

Cisco UCS X-Series Direct is a new architecture that integrates a pair of Cisco UCS Fabric Interconnect 9108 100G with Cisco UCS X9508 Chassis and Cisco UCS X-Series Compute nodes to deliver the UCS X-Series Direct solution. 

For a quick overview of Cisco UCS X-Series capabilities and features, see link:https://www.cisco.com/c/en/us/products/collateral/servers-unified-computing/ucs-x-series-modular-system/ucs-x-series-direct-aag.html[Cisco UCS X-Series Direct At-a-Glance^].
 
Cisco UCS X-Series Direct consists of the following components:

* Cisco UCS 9108 100G Fabric Interconnect
* Cisco UCS X9508 Chassis
* Cisco UCS X-Series Compute Nodes
* Optional components: 
    ** PCIe Nodes and X-Fabric Module
    ** Second Cisco UCS X9508 Chassis with X-Series Compute Nodes and Cisco UCS 9108-100G Intelligent Fabric Modules and up to four C-Series Rack Servers

Refer to the technical specifications for each of these components in the sections above for more information about the Cisco UCS X-Series Direct solution components.

[NOTE]
Refer to this link for the complete technical specification for UCS X-Series Direct: https://www.cisco.com/c/en/us/products/collateral/servers-unified-computing/ucs-x-series-modular-system/ucs-x-series-direct-ds.html[Cisco UCS X-Series Direct Datasheet].

== Cisco UCS C-Series rack server options

Cisco UCS C-Series Rack Servers are available in one, two and four rack-unit (RU) varieties, with various CPU, memory, and I/O options. The part numbers that are listed in the second table below are for the base server. They do not include CPUs, memory, drives, Peripheral Component Interconnect Express (PCIe) cards. Multiple configuration options are available and are supported in the FlexPod architecture.

The following table lists the Cisco UCS C-Series Rack Server options.

|===
|Cisco UCS C-Series rack server |Part number |Technical specifications

|Cisco UCS C220 M7
|UCSC-C220-M7
|
https://www.cisco.com/c/en/us/products/collateral/servers-unified-computing/ucs-c-series-rack-servers/ucs-c220-m7-rack-server-ds.html[Cisco UCS C220 M7 Rack Server]
|Cisco UCS C220 M8
|UCSC-C220-M8
|
https://www.cisco.com/c/en/us/products/collateral/servers-unified-computing/ucs-c-series-rack-servers/ucs-c220-m8-rack-server-ds.html[Cisco UCS C220 M8 Rack Server]
|Cisco UCS C225 M6
|UCSC-C225-M6
|
https://www.cisco.com/c/en/us/products/collateral/servers-unified-computing/ucs-c-series-rack-servers/ucs-c225-m6-sff-rack-server-ds.html[Cisco UCS C225 M6 Rack Server]
|Cisco UCS C225 M8
|UCSC-C225-M8
|
https://www.cisco.com/c/en/us/products/collateral/servers-unified-computing/ucs-c-series-rack-servers/ucs-c225-m8-rack-server-ds.html[Cisco UCS C225 M8 Rack Server]
|Cisco UCS C240 M7
|UCSC-C240-M7
|
https://www.cisco.com/c/en/us/products/collateral/servers-unified-computing/ucs-c-series-rack-servers/ucs-c240-m7-rack-server-ds.html[Cisco UCS C240 M7 Rack Server]
|Cisco UCS C240 M8
|UCSC-C240-M8
|
https://www.cisco.com/c/en/us/products/collateral/servers-unified-computing/ucs-c-series-rack-servers/ucs-c240-m8-rack-server-ds.html[Cisco UCS C240 M8 Rack Server]
|Cisco UCS C245 M6
|UCSC-C245-M6
|
https://www.cisco.com/c/en/us/products/collateral/servers-unified-computing/ucs-c-series-rack-servers/ucs-c245-m6-sff-rack-server-ds.html[Cisco UCS C245 M6 Rack Server]
|Cisco UCS C245 M8
|UCSC-C245-M8
|
https://www.cisco.com/c/en/us/products/collateral/servers-unified-computing/ucs-c-series-rack-servers/ucs-c245-m8-rack-server-ds.html[Cisco UCS C245 M8 Rack Server]
|===


The following table lists the Cisco UCS C-Series rack servers optimized for AI usecases:

|===
|Cisco UCS C-Series rack server |Part number |Technical specifications

|Cisco UCS C845A M8
|UCSC-C845A-M8
|
https://www.cisco.com/c/en/us/products/collateral/servers-unified-computing/ucs-c-series-rack-servers/ucs-c845a-m8-rack-server-ds.html[Cisco UCS C845A M8 Rack Server]
|Cisco UCS C880A M8
|UCSC-C880A-M8
|
https://www.cisco.com/c/en/us/products/collateral/servers-unified-computing/ucs-c-series-rack-servers/ucs-c880a-m8-rack-server-ds.html[Cisco UCS C880A M8 Rack Server]
|Cisco UCS C885A M8
|UCSC-C885A-M8
|
https://www.cisco.com/c/en/us/products/collateral/servers-unified-computing/ucs-c-series-rack-servers/ucs-c885a-m8-ds.html[Cisco UCS C885A M8 Rack Server]
|===

Previous generations of Cisco UCS C-Series servers can be used in the FlexPod architecture, if they are supported on the https://ucshcltool.cloudapps.cisco.com/public/[Cisco UCS Hardware and Software Compatibility List^]. 

== Cisco Nexus 9000 series switch options

Redundant Cisco Nexus 9000 Series Switches are required in the FlexPod architecture. The part numbers that are listed in the table below are for the Cisco Nexus 9000 Series chassis; they do not include SFP modules or Ethernet modules.

|===
|Cisco Nexus switch - Fixed|Technical specifications

|Cisco Nexus 9200 series switch
|
https://www.cisco.com/c/en/us/products/collateral/switches/nexus-9000-series-switches/datasheet-c78-735989.html[Cisco Nexus 9200 Series Switches]
|Cisco Nexus 9300 series switch
|
https://www.cisco.com/c/en/us/products/collateral/switches/nexus-9000-series-switches/datasheet-c78-736967.html[Cisco Nexus 9300 Series Switches]
|===

|===
|Cisco Nexus switch - Modular  |Technical specifications

|Cisco Nexus 9400 series switch
|
https://www.cisco.com/c/en/us/products/collateral/switches/nexus-9000-series-switches/nexus9400-series-switches-ds.html?ccid=cc002962&oid=dstdnc029385[Cisco Nexus 9400 Series Switches]
|Cisco Nexus 9500 series switch
|
https://www.cisco.com/c/en/us/products/collateral/switches/nexus-9000-series-switches/datasheet-c78-729404.html[Cisco Nexus 9500 Series Switches]
|Cisco Nexus 9800 series switch
|
https://www.cisco.com/c/en/us/products/collateral/switches/nexus-9000-series-switches/nexus9800-series-switches-ds.html?ccid=cc002962&oid=dstdnc029386[Cisco Nexus 9800 Series Switches]
|===

== Cisco APIC options
Cisco APIC is the main architectural component of Cisco ACI. It is the unified point of automation and management for the Cisco ACI fabric.

For more information about APIC product specifications refer to Table 1 through Table 3 on the https://www.cisco.com/c/en/us/products/collateral/cloud-systems-management/application-policy-infrastructure-controller-apic/datasheet-c78-739715.html[Cisco Application Policy Infrastructure Controller Datasheet^].

== Cisco MDS options

Cisco MDS switches are an optional component in the FlexPod architecture. Redundant SAN switch fabrics are required when you implement the Cisco MDS switch for FC SAN. The table below lists the supported Cisco MDS switches. See the https://mysupport.netapp.com/matrix/[NetApp IMT^] and https://ucshcltool.cloudapps.cisco.com/public/[Cisco Hardware and Software Compatibility List^] for a complete list of supported SAN switches.

|===
|Cisco MDS Switch |Description

|Cisco MDS 9100 Series Switches
|
http://www.cisco.com/c/en/us/products/storage-networking/mds-9100-series-multilayer-fabric-switches/datasheet-listing.html[Cisco MDS 9100 Series Switches]
|Cisco MDS 9200 Series Switches
|
https://www.cisco.com/c/en/us/products/storage-networking/mds-9200-series-multiservice-switches/datasheet-listing.html[Cisco MDS 9200 Series Switches]
|Cisco MDS 9300 Series Switches
|
https://www.cisco.com/c/en/us/products/storage-networking/mds-9300-series-multilayer-fabric-switches/datasheet-listing.html[Cisco MDS 9300 Series Switches]
|Cisco MDS 9700 Series directors
|
http://www.cisco.com/c/en/us/products/storage-networking/mds-9700-series-multilayer-directors/datasheet-listing.html[Cisco MDS 9700 Series Switches]
|===

== Cisco support licensing options

Valid TSANet support contracts are required on all Cisco equipment in the FlexPod Datacenter architecture.

[NOTE]
The required licenses and corresponding part numbers can vary by product and configuration. It is recommended to confirm licensing requirements with your Cisco or NetApp sales representative prior to ordering.

The following table lists the Cisco support licensing options.

|===
|Cisco Support licensing |License guide

|TSANet
|
https://www.tsanet.org/cisco-tsanet-case-study/
|===
