---
sidebar: sidebar
permalink: fp-def/fp-express-tech-spec_connectivity_requirements.html
keywords: connectivity, requirements, flexpod, express, aff, fas, asa
summary: This section describes the connectivity requirements for the different versions of FlexPod Express.
---

= Connectivity requirements
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ./../media/



[.lead]
This section describes the general connectivity requirements for the different versions of FlexPod Express.

== Connectivity requirements for FlexPod Express with NetApp AFF/ ASA/ FAS

The connectivity requirements for FlexPod Express with NetApp AFF/ ASA/ FAS generally include:

* NetApp storage controllers must be directly connected to the Cisco Nexus switches.
* For Cisco UCS X-Series Direct deployments, the NetApp storage controllers can be connected directly to the embedded Fabric Interconnects.
* No additional equipment can be placed inline between the core FlexPod components.
* Virtual port channels (vPCs) are required to connect the Cisco Nexus 9000 series switches to the NetApp storage controllers.
* Although it is not required, enabling jumbo frame support is recommended throughout the environment.
