---
sidebar: sidebar
permalink: fp-def/fp-express-tech-spec_cisco_components.html
keywords: cisco, components, server, options, rack, ucs, nexus, switches, x-series-direct, c-series
summary: Cisco is a substantial contributor to the FlexPod Express design and architecture; it contributes the compute and networking layers of the solution.
---

= Cisco components
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ./../media/


[.lead]
Cisco is a substantial contributor to the FlexPod Express design and architecture; it contributes the compute and networking layers of the solution. This section describes the Cisco UCS and Cisco Nexus components that are available for FlexPod Express.

== Cisco UCS X-Series Direct 

Cisco UCS X-Series Direct is a new architecture that integrates a pair of Cisco UCS Fabric Interconnect 9108 100G with Cisco UCS X9508 Chassis and Cisco UCS X-Series Compute nodes to deliver the UCS X-Series Direct solution. 

For a quick overview of Cisco UCS X-Series capabilities and features, see link:https://www.cisco.com/c/en/us/products/collateral/servers-unified-computing/ucs-x-series-modular-system/ucs-x-series-direct-aag.html[Cisco UCS X-Series Direct At-a-Glance^].
 
Cisco UCS X-Series Direct consists of the following components:

* Cisco UCS 9108 100G Fabric Interconnect
* Cisco UCS X9508 Chassis
* Cisco UCS X-Series Compute Nodes
* Optional components: 
    ** PCIe Nodes and X-Fabric Module
    ** Second Cisco UCS X9508 Chassis with X-Series Compute Nodes and Cisco UCS 9108-100G Intelligent Fabric Modules and up to four C-Series Rack Servers

[NOTE]
Refer to this link for the complete technical specification for UCS X-Series Direct: https://www.cisco.com/c/en/us/products/collateral/servers-unified-computing/ucs-x-series-modular-system/ucs-x-series-direct-ds.html[Cisco UCS X-Series Direct Datasheet].



Refer to the tables below for the technical specifications for the X-Series Direct components.

|===
|Cisco UCS X-Series Direct fabric interconnect |Part number |Technical specifications

|UCS 9108 100G Fabric Interconnect
|UCSX-S9108-100G
|
https://www.cisco.com/c/dam/en/us/products/collateral/servers-unified-computing/ucs-x-series-modular-system/ucs-fabric-interconnect-9108-100g.pdf[Cisco UCS 9108 Fabric Interconnect]
|===


|===
|Cisco UCS X-Series Direct Chassis|Part number |Technical specifications

|Cisco UCS X9508 Chassis
|UCSX-9508
|
https://www.cisco.com/c/en/us/products/collateral/servers-unified-computing/ucs-x-series-modular-system/datasheet-c78-2472574.html?ccid=cc002456&oid=dstcsm026317[Cisco UCS X9508 Chassis]
|===


|===
|Cisco UCS X-Series Direct compute nodes |Part number |Technical specifications

|Cisco UCS X210c M7
|UCSX-210C-M7
|
https://www.cisco.com/c/en/us/products/collateral/servers-unified-computing/ucs-x-series-modular-system/ucs-x210c-m7-compute-node-ds.html[Cisco UCS X210c M7 Compute Node]
|Cisco UCS X210c M8
|UCSX-210C-M8
|
https://www.cisco.com/c/en/us/products/collateral/servers-unified-computing/ucs-x-series-modular-system/ucs-x210c-m8-compute-node-ds.html[Cisco UCS X210c M8 Compute Node]
|Cisco UCS X215c M8
|UCSX-215C-M8
|
https://www.cisco.com/c/en/us/products/collateral/servers-unified-computing/ucs-x-series-modular-system/ucs-x215c-m8-compute-node-ds.html[Cisco UCS X215c M8 Compute Node]
|Cisco UCS X410c M7
|UCSX-410C-M7
|
https://www.cisco.com/c/en/us/products/collateral/servers-unified-computing/ucs-x-series-modular-system/ucs-x410c-m7-compute-node-ds.html[Cisco UCS X410c M7 Compute Node]
|Cisco UCS X410c M8
|UCSX-410C-M8
|
https://www.cisco.com/c/en/us/products/collateral/servers-unified-computing/ucs-x-series-modular-system/ucs-x410c-m8-compute-node-ds.html[Cisco UCS X410c M8 Compute Node]
|===

|===
|Cisco UCS X-Series Direct Modules |Part number |Technical specifications

|Cisco UCS 9108 Intelligent Fabric Module
|UCSX-I-9108-100G
|
https://www.cisco.com/c/dam/en/us/products/collateral/servers-unified-computing/ucs-x-series-modular-system/cisco-ucs-9108-100g-intelligent-fabric-module-spec-sheet.pdf[Cisco UCS 9108 Intelligent Fabric Module]
|Cisco UCS X9416 X-Fabric Module
|UCSX-FS-9416
|
https://www.cisco.com/c/en/us/products/collateral/servers-unified-computing/ucs-x-series-modular-system/solution-overview-c22-2432175.html?ccid=cc002456&oid=sowcsm025665[Cisco UCS X9416 X-Fabric Module]
|Cisco UCS X440p PCIe Node
|UCSX-440P
|https://www.cisco.com/c/en/us/products/collateral/servers-unified-computing/ucs-x-series-modular-system/ucs-x440p-pcle-node-ds.html[Cisco UCS X440p PCIe Node]
|===

== Cisco Unified Edge

Cisco Unified Edge is an AI-ready system that redefines computing at the edge by converging compute, networking, storage, and security. The modular design is future-ready, energy-efficient, and easy-to-service and can be tailored to support today’s workloads and use cases while remaining adaptable to the rapidly evolving AI landscape.

For a quick overview of Cisco Unified Edge capabilities and features, see link:https://www.cisco.com/c/en/us/products/collateral/servers-unified-computing/unified-edge/unified-edge-at-a-glance.html[Cisco Unified Edge At-a-Glance.^]

Cisco Unified Edge consists of the following components:

    * Cisco UCS XE9305 Chassis
    * Compute Nodes - Choice of
        ** Cisco UCS XE130c M8 Compute Node
        ** Cisco UCS XE150c M8 Compute Node
        ** Cisco 8255 G2 Secure Router Node

The tables below list the Cisco Unified Edge chassis and compute nodes options.
|===
|Cisco Unified Edge chassis |Part number |Technical specifications

|Cisco UCS XE9305 Chassis
|UCSXE-9305-U
|
https://www.cisco.com/c/dam/en/us/products/collateral/servers-unified-computing/ucs-c-series-rack-servers/ucs-xe9305-m8-chassis-spec-sheet.pdf[Cisco UCS XE9305 Chassis]
|===    

|===
|Cisco Unified Edge compute nodes |Part number |Technical specifications

|Cisco UCS XE130c M8 Compute Node
|UCSXE-130C-M8
|
https://www.cisco.com/c/dam/en/us/products/collateral/servers-unified-computing/ucs-c-series-rack-servers/ucs-xe130c-m8-compute-node-spec-sheet.pdfl[Cisco UCS XE130c M8 Compute Node]
|Cisco UCS XE150c M8 Compute Node
|UCSXE-150C-M8
|
https://www.cisco.com/site/us/en/products/collateral/computing/unified-edge/ucs-xe150c-m8-compute-node-ds.html[Cisco UCS XE150c M8 Compute Node]
|Cisco 8255 G2 Secure Router Node
|C8255-G2
|
https://www.cisco.com/site/us/en/products/collateral/networking/sdwan-routers/8000-secure-routers/8200-series-secure-routers-ds.html[Cisco 8255 G2 Secure Router Node]
|===


== Cisco UCS C-Series rack server options

Cisco UCS C-Series Rack Servers are available in one and two rack-unit (RU) varieties, with various CPU, memory, and I/O options. The part numbers that are listed in the following table are for the base servers. They do not include CPUs, memory, drives, Peripheral Component Interconnect Express (PCIe) cards. Multiple configuration options are available and are supported in the FlexPod architecture.

The following table lists the Cisco UCS C-Series Rack Server options.

|===
|Cisco UCS C-Series rack server |Part number |Technical specifications

|Cisco UCS C220 M7
|UCSC-C220-M7
|
https://www.cisco.com/c/en/us/products/collateral/servers-unified-computing/ucs-c-series-rack-servers/ucs-c220-m7-rack-server-ds.html[Cisco UCS C220 M7 Rack Server]
|Cisco UCS C220 M8
|UCSC-C220-M8
|
https://www.cisco.com/c/en/us/products/collateral/servers-unified-computing/ucs-c-series-rack-servers/ucs-c220-m8-rack-server-ds.html[Cisco UCS C220 M8 Rack Server]
|Cisco UCS C225 M6
|UCSC-C225-M6
|
https://www.cisco.com/c/en/us/products/collateral/servers-unified-computing/ucs-c-series-rack-servers/ucs-c225-m6-sff-rack-server-ds.html[Cisco UCS C225 M6 Rack Server]
|Cisco UCS C225 M8
|UCSC-C225-M8
|
https://www.cisco.com/c/en/us/products/collateral/servers-unified-computing/ucs-c-series-rack-servers/ucs-c225-m8-rack-server-ds.html[Cisco UCS C225 M8 Rack Server]
|Cisco UCS C240 M7
|UCSC-C240-M7
|
https://www.cisco.com/c/en/us/products/collateral/servers-unified-computing/ucs-c-series-rack-servers/ucs-c240-m7-rack-server-ds.html[Cisco UCS C240 M7 Rack Server]
|Cisco UCS C240 M8
|UCSC-C240-M8
|
https://www.cisco.com/c/en/us/products/collateral/servers-unified-computing/ucs-c-series-rack-servers/ucs-c240-m8-rack-server-ds.html[Cisco UCS C240 M8 Rack Server]
|Cisco UCS C245 M6
|UCSC-C245-M6
|
https://www.cisco.com/c/en/us/products/collateral/servers-unified-computing/ucs-c-series-rack-servers/ucs-c245-m6-sff-rack-server-ds.html[Cisco UCS C245 M6 Rack Server]
|Cisco UCS C245 M8
|UCSC-C245-M8
|
https://www.cisco.com/c/en/us/products/collateral/servers-unified-computing/ucs-c-series-rack-servers/ucs-c245-m8-rack-server-ds.html[Cisco UCS C245 M8 Rack Server]
|===


== Cisco Nexus Switches

Redundant Cisco Nexus Switches are required in the FlexPod architecture.

|===
|Cisco Nexus switch |Technical specifications

|Cisco Nexus 9200 series switch
|
https://www.cisco.com/c/en/us/products/collateral/switches/nexus-9000-series-switches/datasheet-c78-735989.html[Cisco Nexus 9200 Series Switches]
|Cisco Nexus 9300 series switch
|
https://www.cisco.com/c/en/us/products/collateral/switches/nexus-9000-series-switches/datasheet-c78-736967.html[Cisco Nexus 9300 Series Switches]
|===


== Cisco Support licensing options

Valid TSANet support contracts are required on all Cisco equipment in the FlexPod Express architecture.

[NOTE]
The required licenses and corresponding part numbers can vary by product and configuration. It is recommended to confirm licensing requirements with your Cisco or NetApp sales representative prior to ordering.

The following table lists the Cisco support licensing options.

|===
|Cisco Support licensing |License guide

|TSANet
|
https://www.tsanet.org/cisco-tsanet-case-study/
|===
