---
sidebar: sidebar
permalink: fp-def/fp-express-tech-spec_technical_specifications_and_references.html
keywords: technical, specifications, references, servers, ucs, rack, disk, shelves, aff, asa, fas, x-series-direct, c-series, adapters, controllers
summary: This section describes additional important technical specifications for each of the FlexPod Express components.
---

= Technical Specifications and References
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ./../media/


[.lead]
This section describes additional important technical specifications for each of the FlexPod Express components.

== Cisco UCS X-Series Direct chassis

The technical specifications for Cisco UCS X-Series Direct chassis, as shown in the table below, include the following components:

* Number of rack units
* Maximum number of nodes
* Unified Fabric capability
* Number of I/O bays for IFMs

|===
|Component |Cisco UCS X9508 chassis

|Rack units
|7
|Maximum number of nodes
|8
|Capable of Unified Fabric
|Yes
|I/O bays for IFMs
|Two bays for Cisco UCS 9108 Intelligent Fabric Modules (IFMs)

|===

For more information, see the link:https://www.cisco.com/c/en/us/products/collateral/servers-unified-computing/ucs-x-series-modular-system/datasheet-c78-2472574.html[Cisco UCS X9508 X-Series Chassis Datasheet^].

== Cisco UCS X-Series Direct compute node

The technical specifications for Cisco UCS X-Series compute node include the following components:

* Number of processor sockets
* Processor support
* Memory capacity
* Size and speed
* SAN boot support
* Number of mezzanine adapter slots
* I/O maximum throughput
* Form factor
* Maximum number of compute nodes per chassis

Refer to the table below for the technical specifications for Cisco UCS X-Series Direct compute nodes.

|===
|Component | Cisco UCS datasheet
|Cisco UCS X210c M7
|
https://www.cisco.com/c/en/us/products/collateral/servers-unified-computing/ucs-x-series-modular-system/ucs-x210c-m7-compute-node-ds.html[Cisco UCS X210c M7 Compute Node]
|Cisco UCS X210c M8
|
https://www.cisco.com/c/en/us/products/collateral/servers-unified-computing/ucs-x-series-modular-system/ucs-x210c-m8-compute-node-ds.html[Cisco UCS X210c M8 Compute Node]
|Cisco UCS X215c M8
|
https://www.cisco.com/c/en/us/products/collateral/servers-unified-computing/ucs-x-series-modular-system/ucs-x215c-m8-compute-node-ds.html[Cisco UCS X215c M8 Compute Node]
|Cisco UCS X410c M7
|
https://www.cisco.com/c/en/us/products/collateral/servers-unified-computing/ucs-x-series-modular-system/ucs-x410c-m7-compute-node-ds.html[Cisco UCS X410c M7 Compute Node]
|Cisco UCS X410c M8
|
https://www.cisco.com/c/en/us/products/collateral/servers-unified-computing/ucs-x-series-modular-system/ucs-x410c-m8-compute-node-ds.html[Cisco UCS X410c M8 Compute Node]
|===

== Cisco UCS X-Series Direct fabric interconnect

The technical specifications for Cisco UCS X-Series Direct fabric interconnect include form factor, the total number of ports and expansion slots, and throughput capacity. Refer to the table below for Cisco UCS X-Series Direct fabric interconnect datasheet.

|===
|Component |Cisco UCS datasheet

|Cisco UCS 9108 100G Fabric Interconnect
|
https://www.cisco.com/c/dam/en/us/products/collateral/servers-unified-computing/ucs-x-series-modular-system/ucs-fabric-interconnect-9108-100g.pdf[Cisco UCS 9108 100G Fabric Interconnect]
|===

== Cisco UCS XE9305 Chassis (Cisco Unified Edge)

The technical specifications for Cisco UCS XE9305 Chassis, as shown in the table below, include the following components:

|===
|Component |Cisco UCS XE9305 chassis

|Rack units
|3
|Maximum number of nodes
|5 Cisco UCS XE130c M8 Compute Nodes or 2 Cisco UCS XE150c M8 Compute Nodes

|===

For more information, see the link:https://www.cisco.com/c/dam/en/us/products/collateral/servers-unified-computing/ucs-c-series-rack-servers/ucs-xe9305-m8-chassis-spec-sheet.pdf[Cisco UCS XE9305 Chassis datasheet^].


== Cisco UCS Compute Nodes for Cisco Unified Edge

The technical specifications for Cisco UCS compute nodes for Cisco Unified Edge include the following components:

* Number of processor sockets
* Processor support
* GPU Support
* Memory capacity
* Size and speed
* I/O maximum throughput
* Form factor


The compute nodes also support GPU, XE130c M8 supports NVIDIA L4 GPU and the XE150c M8 supports NVIDIA RTX PRO 4500 / 6000 Blackwell Server Edition GPUs. Refer to the table below for the technical specifications for Cisco UCS Unified Edge compute nodes.

|===
|Component | Cisco UCS datasheet
|Cisco UCS XE130c M8 Compute Node
|
https://www.cisco.com/c/dam/en/us/products/collateral/servers-unified-computing/ucs-c-series-rack-servers/ucs-xe130c-m8-compute-node-spec-sheet.pdf[Cisco UCS XE130c M8 Compute Node]
|Cisco UCS XE150c M8 Compute Node
|
https://www.cisco.com/c/dam/en/us/products/collateral/servers-unified-computing/unified-edge/cisco-ucs-xe150c-m8-compute-node.pdf[Cisco UCS XE150c M8 Compute Node]
|===

Refer to link:https://www.cisco.com/c/en/us/products/servers-unified-computing/unified-edge/datasheet-listing.html[Cisco Unified Edge datasheet listing^] for additional details.

== Cisco UCS C-Series rack servers

The technical specifications for the Cisco UCS C-Series rack servers include processor support, maximum memory capacity, the number of PCIe slots, and form factor. For additional details on compatible UCS server models, see the https://ucshcltool.cloudapps.cisco.com/public/[Cisco Hardware Compatibility^] list. 

Refer to the table below for the technical specifications for Cisco UCS C-Series rack servers.

|===
|Component |Cisco UCS datasheet

|Cisco UCS C220 M7
|
https://www.cisco.com/c/en/us/products/collateral/servers-unified-computing/ucs-c-series-rack-servers/ucs-c220-m7-rack-server-ds.html[Cisco UCS C220 M7 Rack Server]
|Cisco UCS C220 M8
|
https://www.cisco.com/c/en/us/products/collateral/servers-unified-computing/ucs-c-series-rack-servers/ucs-c220-m8-rack-server-ds.html[Cisco UCS C220 M8 Rack Server]
|Cisco UCS C225 M6
|
https://www.cisco.com/c/en/us/products/collateral/servers-unified-computing/ucs-c-series-rack-servers/ucs-c225-m6-sff-rack-server-ds.html[Cisco UCS C225 M6 Rack Server]
|Cisco UCS C240 M7
|
https://www.cisco.com/c/en/us/products/collateral/servers-unified-computing/ucs-c-series-rack-servers/ucs-c240-m7-rack-server-ds.html[Cisco UCS C240 M7 Rack Server]
|Cisco UCS C240 M8
|
https://www.cisco.com/c/en/us/products/collateral/servers-unified-computing/ucs-c-series-rack-servers/ucs-c240-m8-rack-server-ds.html[Cisco UCS C240 M8 Rack Server]
|Cisco UCS C245 M6
|
https://www.cisco.com/c/en/us/products/collateral/servers-unified-computing/ucs-c-series-rack-servers/ucs-c245-m6-sff-rack-server-ds.html[Cisco UCS C245 M6 Rack Server]
|Cisco UCS C245 M8
|
https://www.cisco.com/c/en/us/products/collateral/servers-unified-computing/ucs-c-series-rack-servers/ucs-c245-m8-rack-server-ds.html[Cisco UCS C245 M8 Rack Server]
|===

== Cisco Nexus switches

The technical specifications for Cisco Nexus Switches are contained in the datasheet for each model. Specifications include the form factor size; the number of supervisors, fabric module, and line card slots; and the maximum number of ports. These datasheets can be found in the following table.

|===
|Component |Cisco Nexus datasheet

|Cisco Nexus 9200 Series
|
https://www.cisco.com/c/en/us/products/collateral/switches/nexus-9000-series-switches/datasheet-c78-735989.html[Cisco Nexus 9200 Series Switches]
|Cisco Nexus 9300 Series
|
https://www.cisco.com/c/en/us/products/collateral/switches/nexus-9000-series-switches/datasheet-c78-736967.html[Cisco Nexus 9300 Series Switches]
|===

== NetApp storage controllers

The technical specifications for NetApp storage controllers include the platform configuration, max raw capacity, memory, form factor, ONTAP version requirements, disk shelves, etc.

=== NetApp AFF A-Series 

Entry-level NetApp AFF A-Series storage controllers are supported for use in FlexPod Express. Additional information can be found in the https://www.netapp.com/pdf.html?item=/media/7828-ds-3582-aff-a-series-ai-era.pdf[AFF A-series Technical Specifications^] datasheet and in the https://hwu.netapp.com/[NetApp Hardware Universe^]. See the platform-specific documentation listed in the following table for detailed information about a specific AFF Model.

|===
|Component |AFF A-Series controller platform documentation

|NetApp AFF A20
|
https://docs.netapp.com/us-en/ontap-systems/a20-30-50/a20-key-specifications.html#aff-a20-specifications-at-a-glance[AFF A20 Key Specifications]
|NetApp AFF A30
|
https://docs.netapp.com/us-en/ontap-systems/a20-30-50/a30-key-specifications.html#aff-a30-specifications-at-a-glance[AFF A30 Key Specifications]
|===

=== NetApp AFF C-Series 

Entry-level NetApp AFF C-Series storage controllers are supported for use in FlexPod Express. Additional information can be found in the https://www.netapp.com/pdf.html?item=/media/81583-ds-4240-aff-c-series.pdf[AFF C-Series Technical Specifications^] datasheet and in the https://hwu.netapp.com/[NetApp Hardware Universe^]. See the platform- specific documentation listed in the following table for detailed information about a specific AFF Model.

|===
|Component |AFF C-Series controller platform documentation

|NetApp AFF C30
|
https://docs.netapp.com/us-en/ontap-systems/c30-60/c30-key-specifications.html[AFF C30 Key Specifications]
|===
=== NetApp ASA A-Series

Entry-level models of NetApp ASA A-Series storage controllers are supported for use in FlexPod Express. Additional information can be found in the https://www.netapp.com/pdf.html?item=/media/85736-ds-4254-asa.pdf[NetApp ASA A-Series Technical Specifications^] datasheet and in the https://hwu.netapp.com/[NetApp Hardware Universe^]. See the platform- specific documentation listed in the following table for detailed information about a specific ASA Model.

|===
| Component | NetApp ASA A-Series controller platform documentation

| NetApp ASA A20 | https://docs.netapp.com/us-en/ontap-systems/asa-r2-key-specifications/asa-a20-key-specifications.html[ASA A20 Key Specifications]
|NetApp ASA A30 | https://docs.netapp.com/us-en/ontap-systems/asa-r2-key-specifications/asa-a30-key-specifications.html[ASA A30 Key Specifications]
|===

=== NetApp ASA C-Series

Entry-level models of NetApp ASA C-Series storage controllers are supported for use in FlexPod Express. Additional information can be found in the https://www.netapp.com/pdf.html?item=/media/85736-ds-4254-asa.pdf[NetApp ASA C-Series Technical Specifications^] datasheet and in the https://hwu.netapp.com/[NetApp Hardware Universe^]. See the platform- specific documentation listed in the following table for detailed information about a specific ASA Model.

|===
| Component | NetApp ASA C-Series controller platform documentation

| NetApp ASA C30 | https://www.netapp.com/pdf.html?item=/media/85736-ds-4254-asa.pdf[ASA C30 Key Specifications]
|===

=== NetApp FAS Series

Entry-level FAS storage controllers are supported for use in a FlexPod Express. Detailed specifications for all FAS series storage controllers are available in the https://hwu.netapp.com/[NetApp Hardware Universe^]. See the platform-specific documentation listed in the following table for detailed information about a specific FAS model.

|===
|Component |FAS Series controller platform documentation

|FAS2750 Series
|
https://docs.netapp.com/us-en/ontap-systems/fas2700/overview.html[FAS2750 Key Specifications^]
|FAS2820 Series
|
https://docs.netapp.com/us-en/ontap-systems/fas2800/overview.html[FAS2820 Key Specifications^]
|FAS50 Series
|
https://docs.netapp.com/us-en/ontap-systems/fas50/overview.html[FAS50 Key Specifications^]
|===

=== NetApp disk shelves

The technical specifications for NetApp disk shelves include the form factor size, the number of drives per enclosure, and the shelf I/O modules; this documentation can be found in the following table. For more information, refer to the https://hwu.netapp.com/[NetApp Hardware Universe^].

|===
|Component |NetApp FAS/AFF disk shelf documentation

|NetApp DS212C Disk Shelf
|
https://www.netapp.com/data-storage/disk-shelves-storage-media/[DS212C Disk Shelf Documentation]
|NetApp DS224C Disk Shelf
|
https://www.netapp.com/data-storage/disk-shelves-storage-media/[DS224C Disk Shelf Documentation]
|NetApp DS460C Disk Shelf
|
https://www.netapp.com/data-storage/disk-shelves-storage-media/[DS460C Disk Shelf Documentation]
|NetApp NS224 Disk Shelf
|
https://www.netapp.com/data-storage/disk-shelves-storage-media/[NS224 Disk Shelf Documentation]
|NS224 w/NSM 100B Disk Shelf
|
https://www.netapp.com/data-storage/disk-shelves-storage-media/[NS224 w/NSM 100B Disk Shelf Documentation]
|===

=== NetApp drives

The technical specifications for NetApp drives include the form factor size, disk capacity, disk RPM, supporting controllers, and ONTAP version requirements. These specifications can be found in the Drives section of the http://hwu.netapp.com/Drives/Index?queryId=1581392[NetApp Hardware Universe^].
