---
sidebar: sidebar
permalink: fp-def/fp-express-tech-spec_supported_versus_validated_flexpod_configurations.html
keywords: supported, versus, validated, flexpod, express, configurations, imt
summary: The FlexPod architecture is defined by the set of rules described in this document. The hardware components and software configurations must be supported by the Cisco Hardware Compatibility List (HCL) and the NetApp IMT.
---

= Supported versus validated FlexPod configurations
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ./../media/


[.lead]
The FlexPod architecture is defined by the set of rules described in this document. The hardware components and software configurations must be supported by the https://ucshcltool.cloudapps.cisco.com/public/hcl[Cisco Hardware Compatibility List (HCL)^] and the http://mysupport.netapp.com/matrix[NetApp Interoperability Matrix Tool (IMT)^].

Each Cisco Validated Design (CVD) or NetApp Verified Architecture (NVA) represents a validated FlexPod configuration. Cisco and NetApp document these configuration combinations and validate them through extensive end-to-end testing. The FlexPod deployments that deviate from these configurations are fully supported if they follow the guidelines in this document and all the components are listed as compatible in the Cisco HCL and NetApp IMT.

For example, adding additional storage controllers or Cisco UCS servers and upgrading software to newer versions is fully supported if the software, hardware, and configurations meet the guidelines defined in this document.
