---
sidebar: sidebar
permalink: fp-def/fp-express-tech-spec_power_and_cabling_requirements.html
keywords: power, cabling, requirements, flexpod, express, cisco, ucs, minimum, cabling
summary: This section describes the power and minimum cabling requirements for a FlexPod Express design.
---

= Power and cabling requirements
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ./../media/

//
// This file was created with NDAC Version 2.0 (August 17, 2020)
//
// 2021-05-20 13:19:48.619895
//

[.lead]
This section describes the power and minimum cabling requirements for a FlexPod Express design.

== Power requirements

Power requirements for FlexPod Express differ based on the location where the FlexPod Express configuration is installed.

For more data about the maximum power that is required and for other detailed power information, consult the technical specifications for each hardware component.

For detailed Cisco UCS power data, see the http://www.cisco.com/assets/cdc_content_elements/flash/dataCenter/cisco_ucs_power_calculator/[Cisco UCS power calculator^].

For NetApp storage controller power data, see the http://hwu.netapp.com/Controller/Index?platformTypeId=6780858[NetApp Hardware Universe^]. Under *Platforms*, select the storage platform you want to use (for example, AFF A20), select the ONTAP version, and then click *Show Results*. Power cord data is listed in the *Supported Power Cords* section.

== Minimum cable requirements

This section describes the minimum cable requirements for a FlexPod Express design. Most FlexPod implementations require additional cables, but the number varies based on the deployment size and scope.

The following table lists the minimum number of cables required for each device.

|===
|Cisco Nexus Series switches |Cables required

|Cisco Nexus 9200 Series
.2+|At least two 10GbE cables per switch
|Cisco Nexus 9300 Series
|DS212C
.5+|Number of SAS cables depends on specific configuration of disk shelves
|DS224C
|DS460C
|NS224
|NS224 w/NSM100B
|===
