---
sidebar: sidebar
permalink: fp-def/fp-express-tech-spec__netapp_components.html
keywords: storage, controller, options, fas, aff, asa, disk, shelves, licensing, software
summary: NetApp storage controllers provide the storage foundation in the FlexPod Express architecture for both boot and application data storage. This section lists the different NetApp options in the FlexPod Express architecture.
---

= NetApp components
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ./../media/

//
// This file was created with NDAC Version 2.0 (August 17, 2020)
//
// 2021-05-20 13:19:48.611190
//

[.lead]
NetApp storage controllers provide the storage foundation in the FlexPod Express architecture for both boot and application data storage. This section lists the different NetApp options in the FlexPod Express architecture.

== NetApp storage controller options

Redundant AFF, ASA or FAS series controllers are required in the FlexPod Express architecture. The controllers run ONTAP software. When ordering the storage controllers, the preferred software version can be preloaded on the controllers. For ONTAP, the cluster can be deployed either with a pair of cluster interconnect switches or in a switchless cluster configuration.

[NOTE]
Switchless cluster configuration is supported only for a two node configuration. Cluster interconnect switches are required for configurations with more than 4 nodes, and optional for a two node configuration. 

Different options and configurations are available based on the storage platform selected. Consult your sales representative for details about these additional components.

The controller families that are listed in the table below are appropriate for use in a FlexPod solution because their connection to the Cisco Nexus switches is seamless. See the NetApp Hardware Universe for specific compatibility details on each controller model.

|===
|NetApp entry-level storage Family for FlexPod Express| Model | Technical specifications

.2+|AFF A-Series
|A20
.2+|https://www.netapp.com/pdf.html?item=/media/7828-ds-3582-aff-a-series-ai-era.pdf[AFF A-Series Documentation]
|A30
|AFF C-Series
|C30
|https://www.netapp.com/pdf.html?item=/media/81583-ds-4240-aff-c-series.pdf[AFF C-Series Documentation]
.2+|ASA A-Series
|A20
.2+|
https://www.netapp.com/pdf.html?item=/media/85736-ds-4254-asa.pdf[ASA A-Series Documentation]
|A30
|ASA C-Series
|C30
|https://www.netapp.com/pdf.html?item=/media/85736-ds-4254-asa.pdf[ASA C-Series Documentation]
.2+|FAS
|FAS 2750
.2+|
https://www.netapp.com/pdf.html?item=/media/7819-ds-4020.pdf[FAS Documentation]
|FAS 2820
|===


== NetApp disk shelves and disks


A minimum of one NetApp disk shelf is required for all storage controllers.

The selected NetApp shelf type determines which drive types are available within that shelf.

[NOTE]
For all disk shelves and disk part numbers, consult your sales representative.

For more information about the supported drives, click the NetApp Hardware Universe link in the following table and then select Supported Drives.

The following table lists the NetApp disk shelf options, along with the drives supported for each shelf type, which can be found on NetApp Hardware Universe. Follow the Hardware Universe link, select the version of ONTAP you are using, then select the shelf type. Under the shelf image, click Supported Drives to see the drives supported for specific versions of ONTAP and the disk shelves.

|===
|Disk shelf |Technical specifications

|DS212C
.5+|
https://hwu.netapp.com/DetailViews/Home.aspx[Disk Shelves and Storage Media Supported Drives on NetApp Hardware Universe]
|DS224C
|DS460C
|NS224
|NS224 w/NSM100B
|===

== NetApp software licensing options

The following table lists the NetApp software licensing options.

|===
|NetApp Software Licensing |Technical Specifications

|ONTAP base for AFF and FAS 
.2+|Consult your NetApp sales team for more licensing information.
|ONTAP One for SAN for ASA
|===


== NetApp Support licensing options

SupportEdge Premium licenses are required, and the part numbers for those licenses vary based on the options selected in the FlexPod Express design.

The following table lists the NetApp support licensing options for NetApp AFF, ASA, and FAS Storage systems.

|===
|NetApp Support licensing |Part number |Technical specifications

|SupportEdge Premium4 hours onsite; months: 36
|CS-O2-4HR
|
link:https://www.netapp.com/pdf.html?item=/media/19784-ds-3873.pdf[https://www.netapp.com/pdf.html?item=/media/19784-ds-3873.pdf]
|===
