---
sidebar: sidebar
permalink: fp-def/fp-express-tech-spec_power_and_cabling_requirements.html
keywords: power, cabling, requirements, flexpod, express, cisco, ucs, cabling
summary: This section describes the power requirements and disk shelves cabling guidelines for a FlexPod Express design.
---

= Power and cabling guidelines
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ./../media/


[.lead]
This section describes the power requirements and disk shelves cabling guidelines for a FlexPod Express design.

== Power requirements

Power requirements for FlexPod Express differ based on the location where the FlexPod Express configuration is installed.

For more data about the maximum power that is required and for other detailed power information, consult the link:https://docs.netapp.com/us-en/flexpod/fp-def/fp-express-tech-spec_technical_specifications_and_references.html[technical specifications^] for each hardware component.

For detailed Cisco UCS power data, see the http://www.cisco.com/assets/cdc_content_elements/flash/dataCenter/cisco_ucs_power_calculator/[Cisco UCS power calculator^].

For NetApp storage controller power data, see the http://hwu.netapp.com/Controller/Index?platformTypeId=6780858[NetApp Hardware Universe^]. Under *Platforms*, select the storage platform you want to use (for example, AFF A20), select the ONTAP version, and then click *Show Results*. Power cord data is listed in the *Supported Power Cords* section.

== Disk shelves cabling guidelines

This section provides general guidelines for the cabling of disk shelves.

|===
|Disk shelf |Cabling guidelines
|DS212C
.3+|link:https://docs.netapp.com/us-en/ontap-systems/sas3/install-cabling-rules.html#configuration-rules[SAS cabling rules^]
|DS224C
|DS460C
|NS224
.2+|link:https://docs.netapp.com/us-en/ontap-systems/drive-shelves/index.html[NS224 shelf requirements and  best practices^]
|NS224 w/NSM100B
|===
