---
sidebar: sidebar
permalink: fp-def/fp-express-tech-spec_netapp_components.html
keywords: storage, controller, options, fas, aff, asa, disk, shelves, licensing, software
summary: NetApp storage controllers provide the storage foundation in the FlexPod Express architecture for both boot and application data storage. This section lists the different NetApp storage options in the FlexPod Express architecture.
---

= NetApp components
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ./../media/


[.lead]
NetApp storage controllers provide the storage foundation in the FlexPod Express architecture for both boot and application data storage. This section lists the different NetApp options in the FlexPod Express architecture.

== NetApp storage controller options

Redundant AFF, ASA or FAS series controllers are required in the FlexPod Express architecture. The controllers run ONTAP software. When ordering the storage controllers, the preferred software version can be preloaded on the controllers. For ONTAP, the cluster can be deployed either with a pair of cluster interconnect switches or in a switchless cluster configuration.

[NOTE]
A switchless cluster configuration is supported only for a two node configuration. Cluster interconnect switches are required for configurations with more than 4 nodes, and optional for a two node configuration. 

Different options and configurations are available based on the storage platform selected. Consult your sales representative for details about these additional components.

The controller families that are listed in the table below are appropriate for use in a FlexPod solution because their connection to the Cisco Nexus switches is seamless. See the http://hwu.netapp.com/[NetApp Hardware Universe^] for specific compatibility details on each controller model.

|===
|NetApp entry-level storage Family for FlexPod Express| Model | Technical specifications

.2+|AFF A-Series
|A20
.2+|https://www.netapp.com/pdf.html?item=/media/7828-ds-3582-aff-a-series-ai-era.pdf[AFF A-Series Documentation]
|A30
|AFF C-Series
|C30
|https://www.netapp.com/pdf.html?item=/media/81583-ds-4240-aff-c-series.pdf[AFF C-Series Documentation]
.2+|ASA A-Series
|A20
.2+|https://www.netapp.com/pdf.html?item=/media/85736-ds-4254-asa.pdf[ASA A-Series Documentation]
|A30
|ASA C-Series
|C30
|https://www.netapp.com/pdf.html?item=/media/85736-ds-4254-asa.pdf[ASA C-Series Documentation]
.2+|FAS
|FAS 2750
.2+|https://www.netapp.com/pdf.html?item=/media/7819-ds-4020.pdf[FAS Documentation]
|FAS 2820
|===


== NetApp disk shelves and disks


A minimum of one NetApp disk shelf is required for the storage controllers.

The selected NetApp shelf type determines which drive types are available within that shelf.

[NOTE]
For all disk shelves and disk part numbers, consult your sales representative.


The following table lists the NetApp disk shelf options for FlexPod Express along with links to its technical specifications. 

To get the list of supported drives for your disk shelf, go to link:https://hwu.netapp.com/DetailViews/Home.aspx[NetApp Hardware Universe^], under *Products>Storage>Shelves* select *ONTAP (AFF,ASA,FAS)* , select the version of ONTAP you are using, then select the shelf type (example: DS212C) and click on *Show Results*. Click on *Supported Drives* to see the drives supported for specific versions of ONTAP and the disk shelves.

|===
|Disk shelf |Technical specifications

|DS212C
.5+|
https://www.netapp.com/data-storage/disk-shelves-storage-media/[Disk Shelves and Storage Media Supported Drives on NetApp Hardware Universe]
|DS224C
|DS460C
|NS224
|NS224 w/NSM100B
|===

== NetApp software licensing options

The following table lists the NetApp software licensing options.

|===
|NetApp Software Licensing |Technical Specifications

|ONTAP One for AFF and FAS 
.2+|Consult your NetApp sales team for more licensing information.
|ONTAP One for SAN for ASA
|===

Refer to this link for more information about NetApp software licensing: https://docs.netapp.com/us-en/ontap/system-admin/manage-licenses-concept.html#licenses-included-with-ontap-one[NetApp Software Licensing^].

== NetApp Support licensing options

SupportEdge Premium licenses are required, and the part numbers for those licenses vary based on the options selected in the FlexPod Express design.

The following table lists the NetApp support licensing options for NetApp AFF, ASA, and FAS Storage systems.

|===
|NetApp Support licensing |Technical specifications

|NetApp SupportEdge
|
https://www.netapp.com/netapp-services/
|===
