---
sidebar: sidebar
permalink: fp-def/fp-express-tech-spec_overview.html
keywords: flexpod, express, technical, specifications, architecture, cisco, ucs, netapp, aff, asa, fas
summary: FlexPod Express is a predesigned, best practice architecture that is built on the Cisco Unified Computing System (Cisco UCS) and the Cisco Nexus family of switches, and the storage layer is built by using the NetApp AFF, ASA, or FAS storage systems.
---

= FlexPod Express Technical Specifications
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ./../media/


[.lead]
FlexPod Express is a predesigned, best practice architecture that is built on the Cisco Unified Computing System (Cisco UCS) and the Cisco Nexus family of switches, and the storage layer is built by using the NetApp AFF, ASA, or FAS entry-level storage systems. FlexPod Express is a suitable platform for running various virtualization hypervisors, bare metal operating systems (OSs), and enterprise workloads in small-to-medium-sized environments, remote office and branch office (ROBO) deployments, and edge locations.

FlexPod Express delivers not only a baseline configuration, but also the flexibility to be sized and optimized to accommodate many different use cases and requirements.
