---
sidebar: sidebar
permalink: fp-def/fp-express-tech-spec__power_and_cabling_requirements.html
keywords: power, cabling, requirements, flexpod, express, cisco, ucs, minimum, cabling
summary: This section describes the power and minimum cabling requirements for a FlexPod Express design.
---

= Power and cabling requirements
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ./../media/

//
// This file was created with NDAC Version 2.0 (August 17, 2020)
//
// 2021-05-20 13:19:48.619895
//

[.lead]
This section describes the power and minimum cabling requirements for a FlexPod Express design.

== Power requirements

The power requirements are based on U.S. specifications and assume the use of AC power. Other countries might have different power requirements. Direct current (DC) power options are also available for most components. For additional data about the maximum power required as well as other detailed power information, consult the detailed technical specifications for each hardware component.

For detailed Cisco UCS power data, see the http://www.cisco.com/assets/cdc_content_elements/flash/dataCenter/cisco_ucs_power_calculator/[Cisco UCS Power Calculator^].

The following table lists the power ports required per device.

|===
|Cisco Nexus switches |Power cables required

|Cisco Nexus 9200 Series
|2x C13/C14 power cables for each Cisco Nexus 9200 series switch
|Cisco Nexus 9300 Series
|2x C13/C14 power cables for each Cisco Nexus 9300 series switch
|===

|===
|Cisco UCS chassis |Power cables required

|Cisco UCS X9508 Chassis
|2 CAB-US515P-C19-US/CAB-US520-C19-US for each Cisco UCS chassis
|===

|===
|Cisco UCS X-Series Direct Compute Nodes|Power ports required

|Cisco UCS X210c M7
.5+|2 x C13/C14 power cables for each Cisco UCS server
|Cisco UCS X210c M8
|Cisco UCS X215c M8
|Cisco UCS X410c M7
|Cisco UCS X410c M8
|===

|===
|Cisco UCS C-Series servers |Power ports required

|Cisco UCS C220 M7
.8+|2 x C13/C14 power cables for each Cisco UCS server
|Cisco UCS C220 M8
|Cisco UCS C225 M6
|Cisco UCS C225 M8
|Cisco UCS C240 M7
|Cisco UCS C240 M8
|Cisco UCS C245 M6
|Cisco UCS C245 M8
|===

|===
|NetApp Storage controllers |Power ports required (per HA pair)

|AFF : A250,A20, A30 , C30
|2 x C13/C14
|ASA : A20, A30 , C30
|2 x C13/C14
|FAS : 2750 , 2820
|2 x C13/C14
|===


|===
|NetApp Disk shelves |Power ports required

|DS212C
|2 x C13/C14
|DS224C
|2 x C13/C14
|DS460C
|2 x C19/C20 or 2 x C14/C19
|NS224
|2 x C13/C14
|NS224 w/NSM100B
|4 x C13/C14
|===


== Minimum cable requirements

This section describes the minimum cable requirements for a FlexPod Express design. Most FlexPod implementations require additional cables, but the number varies based on the deployment size and scope.

The following table lists the minimum number of cables required for each device.

|===
|Cisco Nexus Series switches |Cables required

|Cisco Nexus 9200 Series
.2+|At least two 10GbE fiber or Twinax cables per switch
|Cisco Nexus 9300 Series
|DS212C
.5+|Number of SAS cables depends on specific configuration of disk shelves
|DS224C
|DS460C
|NS224
|NS224 w/NSM100B
|===
