---
sidebar: sidebar
permalink: fp-def/fp-express-tech-spec_connectivity_requirements.html
keywords: connectivity, requirements, flexpod, express, aff, fas, asa
summary: This section describes the connectivity requirements for the different versions of FlexPod Express.
---

= Connectivity requirements
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ./../media/

//
// This file was created with NDAC Version 2.0 (August 17, 2020)
//
// 2021-05-20 13:19:48.590847
//

[.lead]
This section describes the connectivity requirements for the different versions of FlexPod Express.

== Connectivity requirements for FlexPod Express with NetApp AFF/ ASA/ FAS

The connectivity requirements for FlexPod Express with NetApp AFF/ ASA/ FAS include:

* NetApp storage controllers must be directly connected to the Cisco Nexus switches.
* For UCS X-series Direct deployments, the NetApp storage controllers can be connected directly to the embedded Fabric Interconnects.
* No additional equipment can be placed inline between the core FlexPod components.
* Virtual port channels (vPCs) are required to connect the Cisco Nexus 9000 series switches to the NetApp storage controllers.
* Although it is not required, enabling jumbo frame support is recommended throughout the environment.
