---
sidebar: sidebar
permalink: hybrid-cloud/fpd-ibn-cloud-design.html
keywords: 
summary: 
---

= FlexPod Datacenter with IBM Cloud Private

:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ./../media/

Sreenivasa Edula, Cisco Systems, Inc.
Thanachit Wichianchai (Bank), IBM
Jacky Ben-Bassat, IBM Global Alliance, NetApp

BM Cloud Private (ICP) is an on-premises platform for developing and managing containerized applications for cloud-native and application-modernization use cases. It is an integrated environment built on Kubernetes as its container orchestration, and includes a private image repository for Docker containers, a management console, a monitoring framework, many open source based, as well as IBM containerized applications, and more. Combining ICP with FlexPod, the converged infrastructure from Cisco and NetApp, can simplify the deployment and the management of your infrastructure. You can also benefit from improved storage efficiency, better data protection, lower risk, and the flexibility to scale this highly available enterprise-grade infrastructure stack to accommodate new business requirements and other changes over time.

This combined solution helps organization accelerate their digital transformation journey. For many companies, this means adopting micro-services and DevOps practices and moving away from monolithic application development practices as a first step in creating more business value from their applications.

To help customers, business partners, and other interested parties with their digital transformation and to enhance their cloud-native and application modernization practices, Cisco, NetApp, and IBM partnered to produce this Cisco Validated Design (CVD) for the FlexPod for IBM Cloud Private solution. This document provides a reference architecture that includes design and deployment guidance, best practices, and other recommendations. With this guide, one can simplify the digital transformation and address many of the associated challenges, including cost and risk reduction, scalability, operational flexibility, and security

link:https://www.cisco.com/c/en/us/td/docs/unified_computing/ucs/UCS_CVDs/flexpod_icp_ucsm32.html[FlexPod Datacenter with IBM Cloud Private^]