---
sidebar: sidebar
permalink: hybrid-cloud/gcp-ncvo-conclusion.html
keywords: conclusion
summary: In this solution, the NetApp Cloud Data service, Cloud Volumes ONTAP, and FlexPod Datacenter infrastructure were used to build a DR solution with a public cloud powered by the Cisco Intersight Cloud Orchestrator. The FlexPod solution has constantly evolved to enable customers to modernize their applications and business-delivery processes. With this solution, you can build a BCDR plan with the public cloud as your go-to location for a transient or full-time DR plan while keeping the cost of the DR solution low.
---

= Conclusion
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ./../media/

//
// This file was created with NDAC Version 2.0 (August 17, 2020)
//
// 2022-09-29 18:43:12.733128
//

link:gcp-ncvo-solution-validation.html[Previous: Solution validation.]

[.lead]
In this solution, the NetApp Cloud Data service, Cloud Volumes ONTAP, and FlexPod Datacenter infrastructure were used to build a DR solution with a public cloud powered by the Cisco Intersight Cloud Orchestrator. The FlexPod solution has constantly evolved to enable customers to modernize their applications and business-delivery processes. With this solution, you can build a BCDR plan with the public cloud as your go-to location for a transient or full-time DR plan while keeping the cost of the DR solution low.

Data replication between on-premises FlexPod and NetApp Cloud Volumes ONTAP was handled by proven SnapMirror technology, but you can also select other NetApp data- transfer and synchronization tools like Cloud Sync for your data mobility requirements. Security of the data in-flight provided by built-in encryption technologies based on TLS/AES.

Whether you have a temporary DR plan for an application or a full-time DR plan for a business, the portfolio of products used in this solution can meet both requirements at scale. Powered by Cisco Intersight Workflow Orchestrator, the same can be automated with prebuilt workflows that not just eliminate the need to rebuild processes but also accelerate the implementation of a BCDR plan.

The solution enables the management of FlexPod on-premises and data replication across a hybrid cloud in a very easy and convenient manner with automation and orchestration provided by Cisco Intersight Cloud Orchestrator.

== Where to find additional information

To learn more about the information that is described in this document, review the following documents and/or websites:

=== GitHub

* All Terraform Configurations used
+
https://github.com/ucs-compute-solutions/cvo_snapmirror[https://github.com/ucs-compute-solutions/cvo_snapmirror^] 

* JSON files for importing workflows
+
https://github.com/ucs-compute-solutions/FlexPod_DR_Workflows[https://github.com/ucs-compute-solutions/FlexPod_DR_Workflows^]

=== Cisco Intersight

* Cisco Intersight Help Center
+
https://intersight.com/help/saas/home[https://intersight.com/help/saas/home^]

* Cisco Intersight Cloud Orchestrator Documentation:
+
https://intersight.com/help/appliance/orchestration/configure[https://intersight.com/help/appliance/orchestration/configure^]

* Cisco Intersight Service for HashiCorp Terraform Documentation
+
https://community.cisco.com/t5/data-center-and-cloud-knowledge-base/intersight-service-for-terraform/ta-p/4301093[https://community.cisco.com/t5/data-center-and-cloud-knowledge-base/intersight-service-for-terraform/ta-p/4301093^]

* Cisco Intersight Data Sheet
+
https://www.cisco.com/c/en/us/products/collateral/cloud-systems-management/intersight/intersight-ds.html[https://www.cisco.com/c/en/us/products/collateral/cloud-systems-management/intersight/intersight-ds.html^]

* Cisco Intersight Cloud Orchestrator Data Sheet
+
https://www.cisco.com/c/en/us/products/collateral/cloud-systems-management/intersight/nb-06-intersight-cloud-orch-aag-cte-en.html[https://www.cisco.com/c/en/us/products/collateral/cloud-systems-management/intersight/nb-06-intersight-cloud-orch-aag-cte-en.html^] 

* Cisco Intersight Service for HashiCorp Terraform Data Sheet
+
https://www.cisco.com/c/en/us/products/collateral/cloud-systems-management/intersight/nb-06-intersight-terraf-ser-aag-cte-en.html[https://www.cisco.com/c/en/us/products/collateral/cloud-systems-management/intersight/nb-06-intersight-terraf-ser-aag-cte-en.html^]

=== FlexPod

* FlexPod Home Page
+
https://www.flexpod.com[https://www.flexpod.com^]

* Cisco Validated Design and deployment guides for FlexPod
+
https://www.cisco.com/c/en/us/td/docs/unified_computing/ucs/UCS_CVDs/flexpod_m6_esxi7u2_design.html[FlexPod Datacenter with Cisco UCS 4.2(1) in UCS Managed Mode, VMware vSphere 7.0 U2, and NetApp ONTAP 9.9 Design Guide^]

* FlexPod Datacenter with Cisco UCS X-Series
+
https://www.cisco.com/c/en/us/td/docs/unified_computing/ucs/UCS_CVDs/flexpod_xseries_esxi7u2_design.html[https://www.cisco.com/c/en/us/td/docs/unified_computing/ucs/UCS_CVDs/flexpod_xseries_esxi7u2_design.html^]

=== Interoperability

* NetApp Interoperability Matrix Tool
+
http://mysupport.netapp.com/matrix[http://mysupport.netapp.com/matrix^]


* Cisco UCS Hardware and Software Interoperability Tool
+
http://www.cisco.com/web/techdoc/ucs/interoperability/matrix/matrix.html[http://www.cisco.com/web/techdoc/ucs/interoperability/matrix/matrix.html^]

* VMware Compatibility Guide
+
http://www.vmware.com/resources/compatibility/search.php[http://www.vmware.com/resources/compatibility/search.php^]

=== NetApp Cloud Volumes ONTAP reference documents

* NetApp Console Documentation:
+
https://docs.netapp.com/us-en/console-family/index.html[https://docs.netapp.com/us-en/console-family/index.html^]

* Cloud Volumes ONTAP
+
https://docs.netapp.com/us-en/cloud-manager-cloud-volumes-ontap/task-getting-started-gcp.html

* Google Cloud TCO Calculator with NetApp Cloud Volumes ONTAP
+
https://www.netapp.com/google-cloud/google-cloud-calculator/

* Cloud Volumes ONTAP Sizing and Cost Estimation:
+
https://www.netapp.com/ontap-cloud/pricing/[https://www.netapp.com/ontap-cloud/pricing/^]

* Cloud Assessment and Infrastructure Analysis:
+
https://docs.netapp.com/us-en/data-infrastructure-insights/

* NetApp Hybrid Cloud Solutions:
+
https://www.netapp.com/hybrid-cloud/

* Cloud Manager API documentation
+
https://docs.netapp.com/us-en/occm/reference_infrastructure_as_code.html[https://docs.netapp.com/us-en/occm/reference_infrastructure_as_code.html^]

=== Troubleshooting issues

https://kb.netapp.com/Cloud/ncds/nds/cvo/cvo_kbs[https://kb.netapp.com/Cloud/ncds/nds/cvo/cvo_kbs ^]

=== Terraform

* Terraform Cloud
+
https://www.terraform.io/cloud[https://www.terraform.io/cloud^]

* Terraform Documentation
+
https://www.terraform.io/docs/[https://www.terraform.io/docs/^]

* NetApp Cloud Manager Registry
+
https://registry.terraform.io/providers/NetApp/netapp-cloudmanager/lates[https://registry.terraform.io/providers/NetApp/netapp-cloudmanager/lates^]

=== GCP

* ONTAP High Availability for GCP
+
https://bluexp.netapp.com/blog/gcp-cvo-blg-what-makes-cloud-volumes-ontap-high-availability-for-gcp-tick[https://bluexp.netapp.com/blog/gcp-cvo-blg-what-makes-cloud-volumes-ontap-high-availability-for-gcp-tick^]

* GCP perquisite
+
https://netapp.hosted.panopto.com/Panopto/Pages/Viewer.aspx?id=f3d0368b-7165-4d43-a76e-ae01011853d6[https://netapp.hosted.panopto.com/Panopto/Pages/Viewer.aspx?id=f3d0368b-7165-4d43-a76e-ae01011853d6^]
