---
sidebar: sidebar
permalink: hybrid-cloud/gcp-ncvo-deploy-flexpod.html
keywords: deploy, installation, flexpod
summary: This page lists the resources needed to deploy a FlexPod instance.
---

= Deploy FlexPod
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ./../media/

//
// This file was created with NDAC Version 2.0 (August 17, 2020)
//
// 2022-09-29 18:43:12.515046
//

link:gcp-ncvo-solution-components.html[Previous: Solution components.]

[.lead]
To understand the FlexPod design and deployment details, including the configuration of various elements of design and associated best practices, see https://www.cisco.com/c/en/us/solutions/design-zone/data-center-design-guides/flexpod-design-guides.html[Cisco Validated Designs for FlexPod^].

FlexPod can be deployed in both UCS Managed Mode and Cisco Intersight Managed Mode. If you are deploying FlexPod in UCS Managed Mode, the latest Cisco Validated Design can be found https://www.cisco.com/c/en/us/td/docs/unified_computing/ucs/UCS_CVDs/flexpod_m6_esxi7u2_design.html[here^].  

Cisco Unified Compute System (Cisco UCS) X-Series is a brand new modular compute system, configured and managed from the cloud. It is designed to meet the needs of modern applications and to improve operational efficiency, agility, and scale through an adaptable, future-ready, modular design. The design guidance around incorporating the Cisco Intersight- managed UCS X-Series platform within FlexPod infrastructure can be found https://www.cisco.com/c/en/us/td/docs/unified_computing/ucs/UCS_CVDs/flexpod_xseries_esxi7u2_design.html[here^].  

FlexPod with Cisco ACI deployment can be found https://www.cisco.com/c/en/us/td/docs/unified_computing/ucs/UCS_CVDs/flexpod_esxi65u1_n9k_aci.html[here^].  

link:gcp-ncvo-cisco-intersight-configuration.html[Next: Cisco Intersight configuration.]
