---
sidebar: sidebar
permalink: flexpod-dc/fpd-inter-design.html
keywords: 
summary: 
---

= FlexPod Datacenter with Cisco Intersight and NetApp ONTAP 9.7 - Design Guide

:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ./../media/

John George, Cisco Systems, Inc.
Scott Kovacs, NetApp

This document describes the Cisco and NetApp  solution, which is a validated approach for deploying Cisco and NetApp technologies as shared cloud infrastructure. This validated design provides a framework for deploying VMware vSphere, the most popular virtualization platform in enterprise class data centers, on FlexPod.

FlexPod is a leading integrated infrastructure supporting a broad range of enterprise workloads and use cases. This solution enables customers to quickly and reliably deploy VMware vSphere based private cloud on integrated infrastructure.

link:https://www.cisco.com/c/en/us/td/docs/unified_computing/ucs/UCS_CVDs/fp_dc_ontap_97_ucs_4_vmw_vs_67_U3_design.html[FlexPod Datacenter with Cisco Intersight and NetApp ONTAP 9.7 - Design Guide^]