---
sidebar: sidebar
permalink: security/flexpod-fips-where-to-find-additional-information.html
keywords:
summary:
---

= Acknowledgements, version history, and where to find additional information
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ./../media/
 
link:flexpod-fips-conclusion.html[Previous: Conclusion.]

To learn more about the information that is described in this document, review the following documents and websites:

* Cisco MDS 9000 Family NX-OS Security Configuration Guide
+
https://www.cisco.com/c/en/us/td/docs/switches/datacenter/mds9000/sw/8_x/config/security/cisco_mds9000_security_config_guide_8x/configuring_fips.html#task_1188151

* Cisco Nexus 9000 Series NX-OS Security Configuration Guide, Release 9.3(x)
+
https://www.cisco.com/c/en/us/td/docs/switches/datacenter/nexus9000/sw/93x/security/configuration/guide/b-cisco-nexus-9000-nx-os-security-configuration-guide-93x/m-configuring-fips.html

* NetApp and Federal Information Processing Standard (FIPS) Publication 140-2
+
https://www.netapp.com/company/trust-center/compliance/fips-140-2/

* FIPS 140-2
+
https://fieldportal.netapp.com/content/902303

* NetApp ONTAP 9 Hardening Guide
+
https://www.netapp.com/us/media/tr-4569.pdf

* NetApp Encryption Power Guide
+
https://docs.netapp.com/ontap-9/index.jsp?topic=%2Fcom.netapp.doc.pow-nve%2Fhome.html

* NVE and NAE Datasheet
+
https://www.netapp.com/us/media/ds-3899.pdf

* NSE Datasheet
+
https://www.netapp.com/us/media/ds-3213-en.pdf

* ONTAP 9 Documentation Center
+
http://docs.netapp.com

* NetApp and Federal Information Processing Standard (FIPS) Publication 140-2
+
https://www.netapp.com/company/trust-center/compliance/fips-140-2/

* Cisco and FIPS 140-2 Compliance
+
https://www.cisco.com/c/en/us/solutions/industries/government/global-government-certifications/fips-140.html

* NetApp Cryptographic Security Module
+
https://csrc.nist.gov/csrc/media/projects/cryptographic-module-validation-program/documents/security-policies/140sp2648.pdf

* Cybersecurity practices for medium and large healthcare organizations
+
https://www.phe.gov/Preparedness/planning/405d/Documents/tech-vol2-508.pdf

* Cisco and Cryptographic Module Validation Program (CMVP)
+
https://csrc.nist.gov/projects/cryptographic-module-validation-program/validated-modules/search?SearchMode=Basic&Vendor=cisco&CertificateStatus=Active&ValidationYear=0

* NetApp Storage Encryption, NVMe Self-Encrypting Drives, NetApp Volume Encryption, and NetApp Aggregate Encryption
+
https://www.netapp.com/pdf.html?item=/media/17073-ds-3898.pdf

* NetApp Volume Encryption and NetApp Aggregate Encryption
+
https://www.netapp.com/pdf.html?item=/media/17070-ds-3899.pdf

* NetApp Storage Encryption
+
https://www.netapp.com/pdf.html?item=/media/7563-ds-3213-en.pdf

* FlexPod for Electronic Health Record Systems
+
https://www.netapp.com/pdf.html?item=/media/22199-tr-4881.pdf

* Data Now: Improving Performance in Epic EHR Environments with Cloud-Connected Flash Technology
+
https://www.netapp.com/media/10809-cloud-connected-flash-wp.pdf

* FlexPod Datacenter for Epic EHR Infrastructure
+
https://www.netapp.com/pdf.html?item=/media/17061-ds-3683.pdf

* FlexPod Datacenter for Epic EHR Deployment Guide
+
https://www.netapp.com/media/10658-tr-4693.pdf

* FlexPod Datacenter Infrastructure for MEDITECH Software
+
https://www.netapp.com/media/8552-flexpod-for-meditech-software.pdf

* The FlexPod Standard Extends to MEDITECH Software
+
https://blog.netapp.com/the-flexpod-standard-extends-to-meditech-software/

* FlexPod for MEDITECH Directional Sizing Guide
+
https://www.netapp.com/pdf.html?item=/media/12429-tr4774.pdf

* FlexPod for medical imaging
+
https://www.netapp.com/media/19793-tr-4865.pdf

* AI in Healthcare
+
https://www.netapp.com/us/media/na-369.pdf

* FlexPod for healthcare Ease Your Transformation
+
https://flexpod.com/solutions/verticals/healthcare/

* FlexPod from Cisco and NetApp
+
https://flexpod.com/

== Acknowledgements
* Abhinav Singh, Technical Marketing Engineer, NetApp
* Brian O’Mahony, Solution Architect Healthcare (Epic), NetApp
* Brian Pruitt, Pursuit Business Development Manager, NetApp
* Arvind Ramakrishnan, Senior Solutions Architect, NetApp
* Michael Hommer, FlexPod Global Field CTO, NetApp

== Version History

|===
|Version |Date | Document version history

|Version 1.0
|April 2021
|Initial release

|===
