---
sidebar: sidebar
permalink: ent-db/fpd-oracle-deploy.html
keywords: flexpod, cisco, design, oracle, rac, data, base, ucs, nvme, fibrechannel, fc
summary: "Cisco Validated Designs (CVDs) consist of systems and solutions that are designed, tested, and documented to facilitate and improve customer deployments."
---

= FlexPod Datacenter with Oracle 19c RAC Databases on Cisco UCS and NetApp AFF with NVMe over FibreChannel

:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ./../media/

Tushar Patel, Cisco 
Hardikkumar Vyas, Cisco 

Cisco Validated Designs (CVDs) consist of systems and solutions that are designed, tested, and documented to facilitate and improve customer deployments. This CVD document describes the Cisco and NetApp FlexPod solution, which is a validated approach for deploying a highly available Oracle RAC Database environment. Cisco and NetApp have validated the reference architecture with various database workloads, like OLTP (Online Transactional Processing) and Data Warehouse in Cisco’s UCS Datacenter lab. This document shows the hardware and software configuration of the components involved and the results of various tests. Additionally, the document offers a framework for implementing Oracle RAC Databases on NVMe/FC using Cisco UCS and NetApp Storage System.


link:https://www.cisco.com/c/en/us/td/docs/unified_computing/ucs/UCS_CVDs/flexpod_oracle_ucs_m5.html[FlexPod Datacenter with Oracle 19c RAC Databases on Cisco UCS and NetApp AFF with NVMe over FibreChannel^]
