---
sidebar: sidebar
permalink: ent-db/fpd-sap-fibrechan-ucs.html
keywords: flexpod, cisco, ontap, aff, a400, ucs, intel, xeon, sap, hana
summary: "This document describes the Cisco and NetApp FlexPod Datacenter with NetApp ONTAP 9.7 on NetApp AFF A400 storage and Cisco UCS Manager unified software release 4.1(1) with second-generation Intel Xeon Scalable Processors for SAP HANA in particular."
---

= FlexPod Datacenter for SAP solution using FibreChannel SAN with Cisco UCS Manager 4.0 and NetApp ONTAP 9.7

:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ./../media/

Pramod Ramamurthy, Cisco 
Marco Schoen, NetApp

This document describes the Cisco and NetApp FlexPod Datacenter with NetApp ONTAP 9.7 on NetApp AFF A400 storage and Cisco UCS Manager unified software release 4.1(1) with second-generation Intel Xeon Scalable Processors for SAP HANA in particular.

FlexPod Datacenter with NetApp ONTAP 9.7 and Cisco UCS unified software release 4.1(1) is a pre-designed, best-practice datacenter architecture built on the Cisco Unified Computing System (Cisco UCS), the Cisco Nexus 9000 family of switches, MDS 9000 multilayer fabric switches, and NetApp AFF A-Series storage arrays running ONTAP 9.7 storage OS.

link:https://www.cisco.com/c/en/us/td/docs/unified_computing/ucs/UCS_CVDs/flexpod_sap_ucsm40_fcsan.html[FlexPod Datacenter for SAP solution using FibreChannel SAN with Cisco UCS Manager 4.0 and NetApp ONTAP 9.7^]
