---
sidebar: sidebar
permalink: ent-db/fpd-microsoft-sql-2017-hyper.html
keywords: flexpod, datacenter, microsoft, linux, hyper-v, aff-series, cisco
summary: "This document discusses a FlexPod reference architecture using the latest hardware and software products and provides deployment recommendations for hosting Microsoft SQL Server databases in VMware ESXi and Microsoft Windows Hyper-V virtualized environments with Linux support enablement from Microsoft for SQL Server deployment."
---

= FlexPod Datacenter with Microsoft SQL Server 2017 on Linux VM running on VMware and Hyper-V

:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ./../media/

Gopu Narasimha Reddy, Cisco 
Sanjeev Naldurgkar, Cisco 
Atul Bhalodia, NetApp

[.lead]
This document discusses a FlexPod reference architecture using the latest hardware and software products and provides deployment recommendations for hosting Microsoft SQL Server databases in VMware ESXi and Microsoft Windows Hyper-V virtualized environments with Linux support enablement from Microsoft for SQL Server deployment.

The recommended solution architecture is built on Cisco Unified Computing System (Cisco UCS) using the unified software release 4.0.1c to support the Cisco UCS hardware platforms, including Cisco UCS B-Series Blade Servers, Cisco UCS 6300 Fabric Interconnects, Cisco Nexus 9000 Series Switches, and NetApp AFF Series Storage Arrays.

link:https://www.cisco.com/c/en/us/td/docs/unified_computing/ucs/UCS_CVDs/mssql2017_flexpod_linux.html[FlexPod Datacenter with Microsoft SQL Server 2017 on Linux VM running on VMware and Hyper-V^]
