---
sidebar: sidebar
permalink: ent-db/fpd-sap-cisco-aci-design.html
keywords: flexpod, cisco, ACI, UCS, AFF, A-Series, SAP, HANA, TDI, Nexus 9000, all flash
summary: "This document describes Cisco ACI integrated FlexPod solution as a validated approach for deploying SAP HANA Tailored Data Center Integration (TDI) environments. "
---

= FlexPod Datacenter for SAP solution with Cisco ACI, Cisco UCS Manager 4.0, and NetApp AFF A–Series - Design 

:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ./../media/

Pramod Ramamurthy, Cisco 
Marco Schoen, NetApp

This document describes Cisco ACI integrated FlexPod solution as a validated approach for deploying SAP HANA Tailored Data Center Integration (TDI) environments. This validated design provides guidelines and a framework for implementing SAP HANA with best practices from Cisco and NetApp.

The recommended solution architecture is built on the Cisco Unified Computing System (Cisco UCS) using a unified software release to support Cisco UCS hardware platforms that include the following components:

* Cisco UCS B-Series blade servers and Cisco UCS C-Series rack servers configurable with the Intel Optane Data Center Persistent Memory Module (DCPMM) option

* Cisco UCS 6400 series Fabric Interconnects

* Cisco Nexus 9000 Series Leaf and Spine switches

* NetApp All Flash series storage arrays

Additionally, this document provides validations for both Red Hat Enterprise Linux and SUSE Linux Enterprise Server for SAP HANA.

link:https://www.cisco.com/c/en/us/td/docs/unified_computing/ucs/UCS_CVDs/flexpod_datacenter_ACI_sap_netappaffa_design.html[FlexPod Datacenter for SAP solution with Cisco ACI, Cisco UCS Manager 4.0, and NetApp AFF A–Series - Design^]
