---
sidebar: sidebar
permalink: ent-db/fpd-oracle-rac-aseries.html
keywords: flexpod, cisco, oracle, RAC, UCS, AFF, A-series, CVD
summary: "The FlexPod Datacenter with NetApp All Flash AFF system is a converged infrastructure platform that combines best-of-breed technologies from Cisco and NetApp into a powerful converged platform for enterprise applications."
---

= FlexPod Datacenter with Oracle RAC Databases on Cisco UCS and NetApp AFF A-Series

:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ./../media/

Tushar Patel,  Cisco 
Hardikkumar Vyas, Cisco 

The FlexPod Datacenter with NetApp All Flash AFF system is a converged infrastructure platform that combines best-of-breed technologies from Cisco and NetApp into a powerful converged platform for enterprise applications. Cisco and NetApp work closely with Oracle to support the most demanding transactional and response-time-sensitive databases required by today’s businesses.

This Cisco Validated Design (CVD) describes the reference FlexPod Datacenter architecture using Cisco UCS and NetApp All Flash AFF Storage for deploying a highly available Oracle RAC Database environment. This document shows the hardware and software configuration of the components involved and the results of various tests. Also, this document offers implementation and best practices guidance using Cisco UCS Compute Servers, Cisco Fabric Interconnect Switches, Cisco MDS Switches, Cisco Nexus Switches, NetApp AFF Storage and Oracle RAC Database.  

link:https://www.cisco.com/c/en/us/td/docs/unified_computing/ucs/UCS_CVDs/flexpod_orc12cr2_affaseries.html[FlexPod Datacenter with Oracle RAC Databases on Cisco UCS and NetApp AFF A-Series^]
