---
sidebar: sidebar
permalink: ontap-connector-for-intersight/ci-qsg_new.html
keywords: netapp, cisco, ontap, intersight, flexpod, what's new, features, release notes, enhancements
summary: Cisco Intersight introduces new releases to bring you new features, enhancements, and bug fixes.
---

= What's new
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ./../media/

This section lists new features and functionality available for Cisco Intersight with NetApp ONTAP storage.

== April 2022
NOTE: To ensure compatibility and complete functionality with future releases, it is recommended that you upgrade your NetApp Active IQ Unified Manager to version 9.10P1.

* Added Broadcast Domain to Ethernet Port Detail page
* Changed the term “Aggregate” to “Tier” for the Aggregate and SVM within the user interface
* Changed the term "Cluster Status" to "Array Status"
* MTU filter now works for <,>,=,<=,>= characters
* Added Network Interface Page to Cluster Inventory
* Added AutoSupport to Cluster Inventory
* Added `cdpd.enable` option to node
* Added an object for CDP neighbor
* Added NetApp workflow storage tasks within Cisco Intersight. See link:ci-qsg_use_cases.html[Use case 3 Custom workflows using designer-free form] for a complete list of NetApp storage tasks.

== January 2022
* Added event-based Intersight alarms for NetApp Active IQ Unified Manager 9.10 or above.

NOTE: To ensure compatibility and complete functionality with future releases, it is recommended that you upgrade your NetApp Active IQ Unified Manager to version 9.10.

* Explicitly set each protocol enabled (true or false) for Storage Virtual Machine
* Mapped clusterHealthStatus state ok-with-suppressed to OK
* Renamed Health column to Cluster Status column under the Cluster list page
* Showing storage array “Unreachable” if the cluster is down or otherwise unreachable
* Renamed Health column to Array Status column under the Cluster General page
* SVM now has a “Volumes” tab that shows all the volumes for the SVM
* Volume has a snapshot capacity section
* Licenses now display correctly

== October 2021

* Updated list of NetApp storage tasks available within Cisco Intersight. See link:ci-qsg_use_cases.html[Use case 3 Custom workflows using designer-free form] for a complete list of NetApp storage tasks.
* Added Health column under the Cluster list page.
* Expanded details now available under the General page for a selected cluster.
* NTP Server table now accessible through the navigation pane.
* Added a new Sensors tab containing
 the General page for the Storage Virtual Machine.
* VLAN and link aggregation group summary now available under the Port General page.
* Total Data Capacity column added under the Volume Total Capacity table.
* Latency, IOPS, and Throughput columns added under Average Volume Statistics, Average LUN Statistics, Average Aggregate Statistics, Average Storage VM Statistics, and Average Node Statistics tables
+
NOTE: The above performance metrics are only available for storage arrays monitored through NetApp Active IQ Unified Manager 9.9 or above.
