---
sidebar: sidebar
permalink: ontap-connector-for-intersight/ci-qsg_new.html
keywords: netapp, cisco, ontap, intersight, flexpod, what's new, features, release notes, enhancements
summary: Cisco Intersight introduces new releases to bring you new features, enhancements, and bug fixes.
---

= What's new
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ./../media/

[.lead]
This section lists new features and functionality available for Cisco Intersight with NetApp ONTAP storage.

== January 2024
* NetApp storage orchestration using reference workflows now available for download in GitHub through the https://github.com/ucs-compute-solutions/FlexPod-Intersight-Workflow[FlexPod Intersight Workflow repository^]. For more information on the new reference workflows in GitHub, see link:ci-qsg_use_cases.html[Use case 2: NetApp storage orchestration using Reference Workflows^].

== November 2023
NOTE: An upgrade to NetApp Active IQ Unified Manager 9.14RC1 is required to ensure compatibility and full functionality with the latest release.

* Added NVMe Namespaces page under the Inventory section of the user interface.

== August 2023
NOTE: An upgrade to NetApp Active IQ Unified Manager 9.13GA is required to ensure compatibility and full functionality with the latest release.

* Improved the New NetApp Smart LUN task to clearly indicate the availability of selection options for either creating a new initiator group or selecting an existing initiator group. When users now select the box to create a new initiator group, the parameter for choosing an existing initiator group is no longer available. If users deselect the box to create a new initiator group, the existing initiator group parameter then becomes available. 
* Enhanced the New NetApp LUN Map and Remove NetApp LUN Map tasks. The new relationship between the LUN and initiator group is now updated. The UI inventory is immediately updated for both the LUN and the initiator group upon task execution. 
* The Checks page now loads properly the first-time users log in and no longer requires a refresh.      

== July 2023
NOTE: An upgrade to NetApp Active IQ Unified Manager 9.13GA is required to ensure compatibility and full functionality with the latest release.

* Updated names for NetApp storage tasks. See Use case 3 Custom workflows using designer-free form for the complete list of renamed tasks.
* NFS Interface IP address was added as an output of the New NetApp NAS Smart Volume task. 
* A check that ASUP transport is HTTPS was added to the Checks tab.
* The correct tier type for all tiers now displays properly under the Tiers user interface.
* All compliant licenses now display properly under the Licenses page.
* Accurate value for CIFS shares without or without a home directory now display on the Shares page.
* Sorting and filtering now enabled for the Mapped column on the LUNS page. 
* Sorting and filtering now enabled the Authentication Enabled column on the NTP Servers page. 
* Added new checks and the following corresponding categories to the Checks tab. 
** Security 
** Anti-Ransomware
** Availability
** Other
* Under the Inventory detail view, report now used instead of physical used capacity. 

== June 2023
NOTE: An upgrade to NetApp Active IQ Unified Manager 9.13RC1 is required to ensure compatibility and full functionality with the latest release.  

* Updated names for NetApp storage tasks. See link:ci-qsg_use_cases.html[Use case 3 Custom workflows using designer-free form^] for the complete list of renamed tasks.

== April 2023
* Added Protection Policies (SnapMirror) and Snapshot Policies tabs under the Policies page within the Inventory section of the user interface.
* Added NFS Clients page under the Inventory section of the user interface.  
* Added Protected column in the Storage VMs page under the Inventory section of the user interface.
* Modified how Data Reduction information is reported and displayed.
* Added Local Tier and Cloud Tier tabs under the Tiers page within the Inventory section of the user interface.
* Node column now displays after the Name column under the Ports page within the Inventory section of the user interface.
 
== January 2023 
NOTE: An upgrade to NetApp Active IQ Unified Manager 9.12 GA is required to ensure compatibility and full functionality with the latest release. For a list of known issues related to this release, see <<Known Issues>>.

* Intersight interoperability checks can now distinguish between UCSM and IMM firmware modes when carrying out compatibility checks.
* Protection Relationships will not display in Intersight for ONTAP 9.7. This issue was fixed in ONTAP 9.8RC1.

== August 2022
NOTE: An upgrade to NetApp Active IQ Unified Manager 9.11 GA is required to ensure compatibility and full functionality with the latest release. For a list of known issues related to this release, see <<Known Issues>>.

*	Updated cluster available capacity calculation to match System Manager
* Updated cluster General page to hide the performance metrics summary until performance data is populated
* Fixed cluster General page UI issue that occasionally caused the page to hang
* Added CIFS shares, CIFS services, Qtrees, and SVM SnapMirror policies to backend inventory.
* Added Shares and Qtrees to the UI navigation menu under the Logical inventory section
* Added Shares as a tab from a selected Storage VM
* Added CIFS Service information on the Storage VM General tab if the Storage VM is CIFS enabled
* Added a cluster Checks page that allow users to validate the configuration of NetApp storage systems adhere to best practices

== July 2022
*	Improved visuals for Cluster Data Reduction ratio now available under the Capacity Widget
*	Added FC Interfaces tab to the Network Interfaces page
*	Creating a new volume using the generic “New Storage Volume” task now sets volume space guarantee to none and snapshot reserve percent to 0%
*	Comment field under the Edit Snapshot Policy task now optional and no longer mandatory
*	Improved UI inventory and orchestration consistency
*	Intersight capacity information under Cluster Capacity now consistent with System Manager
*	Added checkbox under New Storage Virtual Machine task to display all parameters when creating a new management interface to improve usability
*	Moved Protocols below Client Match, now consistent with System Manager
*	Export policy general page now displaying Access Protocol(s)
*	igroup removal now conditionally logged
*	Added “Failover Policy” and "autorevert” parameters for NAS under New Storage NAS Data Interface and New Storage iSCSI Data Interface
*	Rollback for New Storage NAS Smart Volume task now removes export policy if no other volumes are attached
*	Made enhancements for Smart Volume and Smart LUN tasks

== April 2022
NOTE: To ensure compatibility and complete functionality with future releases, it is recommended that you upgrade your NetApp Active IQ Unified Manager to version 9.10P1.

* Added Broadcast Domain to Ethernet Port Detail page
* Changed the term “Aggregate” to “Tier” for the Aggregate and SVM within the user interface
* Changed the term "Cluster Status" to "Array Status"
* MTU filter now works for <,>,=,<=,>= characters
* Added Network Interface Page to Cluster Inventory
* Added AutoSupport to Cluster Inventory
* Added `cdpd.enable` option to node
* Added an object for CDP neighbor
* Added NetApp workflow storage tasks within Cisco Intersight. See link:ci-qsg_use_cases.html[Use case 3 Custom workflows using designer-free form^] for a complete list of NetApp storage tasks.

== January 2022
* Added event-based Intersight alarms for NetApp Active IQ Unified Manager 9.10 or above.

NOTE: To ensure compatibility and complete functionality with future releases, it is recommended that you upgrade your NetApp Active IQ Unified Manager to version 9.10.

* Explicitly set each protocol enabled (true or false) for Storage Virtual Machine
* Mapped clusterHealthStatus state ok-with-suppressed to OK
* Renamed Health column to Cluster Status column under the Cluster list page
* Showing storage array “Unreachable” if the cluster is down or otherwise unreachable
* Renamed Health column to Array Status column under the Cluster General page
* SVM now has a “Volumes” tab that shows all the volumes for the SVM
* Volume has a snapshot capacity section
* Licenses now display correctly

== October 2021

* Updated list of NetApp storage tasks available within Cisco Intersight. See link:ci-qsg_use_cases.html[Use case 3 Custom workflows using designer-free form^] for a complete list of NetApp storage tasks.
* Added Health column under the Cluster list page.
* Expanded details now available under the General page for a selected cluster.
* NTP Server table now accessible through the navigation pane.
* Added a new Sensors tab containing
 the General page for the Storage Virtual Machine.
* VLAN and link aggregation group summary now available under the Port General page.
* Total Data Capacity column added under the Volume Total Capacity table.
* Latency, IOPS, and Throughput columns added under Average Volume Statistics, Average LUN Statistics, Average Aggregate Statistics, Average Storage VM Statistics, and Average Node Statistics tables
+
NOTE: The above performance metrics are only available for storage arrays monitored through NetApp Active IQ Unified Manager 9.9 or above.

== Known Issues
* If you are using a version of AIQUM 9.11 or earlier, a discrepancy will occur between the displayed values on the Storage List page and capacity bar chart on the Storage general page. To resolve this issue, upgrade to AIQUM 9.12 or greater to ensure the accuracy of the displayed capacity values. 
* If you are using AIQUM 9.11 or earlier, any checks performed by the "Interoperability" tab under the "Integrated Systems" page will fail to distinguish IMM and UCSM Cisco components accurately. To resolve this issue, upgrade to AIQUM 9.12 to ensure all components are properly identified.
* To ensure Intersight storage inventory data is unaffected during the data collection process, any unsupported ONTAP clusters (i.e., versions below ONTAP 9.7P1) must be removed from the Active IQ Unified Manager (AIQUM).
* All claimed targets require a minimum AIQUM version of 9.11 for FlexPod Integrated System Interoperability queries to complete successfully.
* The Storage Inventory Checks page will not populate if the ONTAP cluster is added to AIQUM using an FQDN. Users must add ONTAP clusters to AIQUM using an IP address.  
